var data = {
	images: [
		{
			src: [""],
			thumbnail: "",
			title: "Placeholder Entry",
			artist: "Placeholder Entry",
			artist_url: null,
			desc: "Do not delete this. You can use this to set the order the tags show up in the dropdown.",
			date_str: "Beginning of Time",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Lucina", "Male Morgan", "Inigo", "Severa", "Male Robin", "Sumia", "Cynthia", "Female Morgan", "Owain", "Gerome", "Virion", "Olivia", "Gaius", "Cordelia", "Vaike", "Lissa", "Frederick", "Cherche", "Soleil", "Caeldori", "Ophelia", "Damien", "Chrobin", "Exalt Family", "Lucinigo", "Sevimorgan", "Robmia", "Owainthia", "Geromorgan", "Viriolivia", "Gaiusdelia", "Vaikessa", "Chercherick", "Roleswap AU", "Modern AU", "Vocaloid", "Kagamine Len"],
			hidden: true
		},	
		{
			src: [""],
			thumbnail: "",
			title: "",
			artist: "",
			artist_url: "",
			desc: "",
			date_str: "",
			tags: [""],
			hidden: true
		},
		{
			src: ["https://cdn.imgchest.com/files/3f62056e63b3.png"],
			thumbnail: "https://cdn.imgchest.com/files/bbf05808f341.png",
			title: "Box Art",
			artist: "SnipperPool",
			artist_url: "https://x.com/SnipperPool",
			desc: "A commission done by a friend, where Morgan and Owain have taken the place of their fathers on the box art. Morgan is in the Grandmaster class while Owain is in the Dread Fighter class. Background edits were done by me.",
			date_str: "May 2021",
			tags: ["Fire Emblem", "Male Morgan", "Owain"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/1bb3093d16ef.png"],
			thumbnail: "https://cdn.imgchest.com/files/c52f7f947077.png",
			title: "The Three Mask-eteers",
			artist: "Riidi",
			artist_url: "https://x.com/m_riidi",
			desc: "A commission of Inigo, Gerome, and Lucina dressed as Roy, Marcus, and Lilina respectively. A little more customization went into Lucina's outfit to reference Robin as her mother.",
			date_str: "April 2021",
			tags: ["Fire Emblem", "Inigo", "Gerome", "Lucina"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/91df7ce44b5d.png"],
			thumbnail: "https://cdn.imgchest.com/files/9693ae8fec50.png",
			title: "The New Pegasus Trio",
			artist: "Riidi",
			artist_url: "https://x.com/m_riidi",
			desc: "A commission of Cynthia, Severa, and Morgan dressed as Palla, Catria, and Est respectively.",
			date_str: "April 2021",
			tags: ["Fire Emblem", "Cynthia", "Severa", "Female Morgan"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/38401c923291.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/be1c2540adfd.png",
			title: "Ballroom Chrom and Robin",
			artist: "Erumei24",
			artist_url: "https://x.com/erumei24",
			desc: "A commission of Chrom and Robin wearing a slightly tweaked version of ballroom Sigurd and Deirdre's outfits. I've always enjoyed the parallels between these two couples, and given how much I also love ballroom dancing, this felt like a no-brainer for me to commission. For a long while, this Robin was also my profile picture on Twitter because of how much I truly adore this piece.",
			date_str: "March 2021",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/2a55bed817ed.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/d96f0c8f30b1.png",
			title: "Wedding Robin and Sumia",
			artist: "Erumei24",
			artist_url: "https://x.com/erumei24",
			desc: "A commission of Robin and Sumia wearing a slightly tweaked version of wedding Marth and Caeda's outfits.  This was a gift for my boyfriend for our anniversary. Sumia as Caeda is obvious, but Robin as Marth is a nod to his support with Tiki in which she outright compares the two and says that Robin is more like Marth than Chrom is. This is also one of my personal favorite pieces that I have ever commissioned.",
			date_str: "March 2021",
			tags: ["Fire Emblem", "Male Robin", "Sumia", "Robmia"],
			hidden: false
		},
			{
			src: ["https://cdn.imgchest.com/files/d86446cb9c0a.png"],
			thumbnail: "https://cdn.imgchest.com/files/01c79a434cd9.png",
			title: "Learning from Dad - Inigo Side",
			artist: "EdithSotoArt",
			artist_url: "https://x.com/EdithSotoArt",
			desc: "Since Lucina inherited her genius from her mother, Inigo thought to impress her by showing off his own tactical prowess. However, chess is a little harder than he expected… Thankfully, his father is a patient teacher, especially when he has his cup of tea to sip on while waiting for Inigo to make his next move.",
			date_str: "March 2021",
			tags: ["Fire Emblem", "Virion", "Inigo", "Lucina", "Viriolivia", "Lucinigo"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/f1b9e6767d6b.png"],
			thumbnail: "https://cdn.imgchest.com/files/d12741cc6e9f.png",
			title: "Learning from Dad - Severa Side",
			artist: "EdithSotoArt",
			artist_url: "https://x.com/EdithSotoArt",
			desc: "While Severa would sooner die than touch a bug, bug-themed cookies were an acceptable enough substitute. After all, the way to a person’s heart is through their stomach… or so her daddy says. And with his help, there was no way she could fail to win Morgan’s favor!",
			date_str: "March 2021",
			tags: ["Fire Emblem", "Gaius", "Cordelia", "Male Morgan", "Gaiusdelia", "Sevimorgan"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/f1ea7100c60f.png"],
			thumbnail: "https://cdn.imgchest.com/files/f1ea7100c60f.png",
			title: "Chrom - Confusion",
			artist: "Rita",
			artist_url: "https://x.com/_anachaga",
			desc: "An emote of Chrom being confused (referred to as Chromfusion). Pairs with the Female Robin one.",
			date_str: "February 2021",
			tags: ["Fire Emblem", "Chrom"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/dca93862517f.png"],
			thumbnail: "https://cdn.imgchest.com/files/dca93862517f.png",
			title: "F!Robin - I See!",
			artist: "Rita",
			artist_url: "https://x.com/_anachaga",
			desc: "A emote of Robin doing the 'naruhodo!' pose. Pairs with the Chrom one.",
			date_str: "February 2021",
			tags: ["Fire Emblem", "Female Robin"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/6206c261de4d.png"],
			thumbnail: "https://cdn.imgchest.com/files/6206c261de4d.png",
			title: "Lucina - Cool Cry",
			artist: "Rita",
			artist_url: "https://x.com/_anachaga",
			desc: "An emote of Lucina with sunglasses crying while doing double fingerguns.",
			date_str: "February 2021",
			tags: ["Fire Emblem", "Lucina"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/2e5268fd9de4.png"],
			thumbnail: "https://cdn.imgchest.com/files/2e5268fd9de4.png",
			title: "M!Morgan - Smug",
			artist: "Rita",
			artist_url: "https://x.com/_anachaga",
			desc: "An emote of Morgan being smug.",
			date_str: "February 2021",
			tags: ["Fire Emblem", "Male Morgan"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/2114c03b4b16.png"],
			thumbnail: "https://cdn.imgchest.com/files/2114c03b4b16.png",
			title: "Sumia - Bashful",
			artist: "Rita",
			artist_url: "https://x.com/_anachaga",
			desc: "An emote of Sumia being bashful, as requested by my boyfriend. Pairs with the Male Robin one.",
			date_str: "February 2021",
			tags: ["Fire Emblem", "Sumia"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/7f59881310e6.png"],
			thumbnail: "https://cdn.imgchest.com/files/7f59881310e6.png",
			title: "M!Robin - Sheepish",
			artist: "Rita",
			artist_url: "https://x.com/_anachaga",
			desc: "An emote of Robin laughing while embarrassed, as requested by my boyfriend. Pairs with the Sumia one.",
			date_str: "February 2021",
			tags: ["Fire Emblem", "Male Robin"],
			hidden: false
		},					
		{
			src: ["https://cdn.imgchest.com/files/5fd89d608dbc.jpeg"],
			thumbnail: "https://cdn.imgchest.com/files/e0d5192a814b.png",
			title: "New Years Chrom and Morgan",
			artist: "Vallurite",
			artist_url: "https://x.com/Vallurite?s=20",
			desc: "Chrom and Morgan are ringing in the New Year with their wonderful new kimonos. And they're not alone, as Chrom has Robin on his hagiota and Morgan has Lucina on his karuta card. Chrom and Lucina's kimonos are based on their design from the Daily Life of Heroes manga, while Morgan and Robin's are my own design. And of course, I couldn't resist giving Morgan the kagami mochi accessory for the cheeky connection to oranges.",
			date_str: "January 2021",
			tags: ["Fire Emblem", "Male Morgan", "Chrom", "Exalt Family"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/37e6483f71a0.png"],
			thumbnail: "https://cdn.imgchest.com/files/4136e13d6fda.png",
			title: "Winter Lucina and Morgan",
			artist: "Majibomber",
			artist_url: "https://x.com/majibomber",
			desc: "Celebrating Christmas with a commission of Lucina and Morgan dressed as their ancestors, Marth and Elice. Background (which is a FEH asset) was added by me! As an aside, this is a period of time where I wasn't consistent with Morgan's eye color hence the blue eyes despite my personal preference for brown eyes on him.",
			date_str: "December 2020",
			tags: ["Fire Emblem", "Lucina", "Male Morgan", "Exalt Family"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/4fae0933463d.png"],
			thumbnail: "https://cdn.imgchest.com/files/28e76c5c8006.png",
			title: "Taking After Their Parents",
			artist: "Nootnootles",
			artist_url: "https://x.com/nootnootles",
			desc: "A commission I got from a friend of mine of the Morgans taking after their parents. Male Morgan is holding Falchion while female Morgan is holding Luna. Some of the details on female Morgan are also based on my boyfriend's preferences, such as having glasses or holding a Piranha 'flower.'",
			date_str: "October 2020",
			tags: ["Fire Emblem", "Male Morgan", "Female Morgan"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/183f4a393132.png"],
			thumbnail: "https://cdn.imgchest.com/files/c91c92b1dc63.png",
			title: "Great Lord Lucina and Bow Knight Inigo",
			artist: "Lace",
			artist_url: "https://bsky.app/profile/adelleein.bsky.social",
			desc: "One of the very first commissions I ever got, which was done for a donation rally. The commission depicts my preferred final classes for Lucina and Inigo, which is Great Lord and Bow Knight respectively. The flower petals around Lucina are a reference to the skill Ignis. The bow sprite is Dignified Bow, and the sword sprite is Skuld.",
			date_str: "August 2020",
			tags: ["Fire Emblem", "Lucina", "Inigo", "Lucinigo"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/08fa2ad5fa25.png"],
			thumbnail: "https://cdn.imgchest.com/files/cff158f2e7c2.png",
			title: "Grandmaster Morgan and Dark Flier Severa",
			artist: "Lace",
			artist_url: "https://bsky.app/profile/adelleein.bsky.social",
			desc: "One of the very first commissions I ever got, which was done for a donation rally. The commission depicts my preferred final classes for Morgan and Severa, which is Grandmaster and Dark Flier respectively. The green tome sprite is Excalibur.",
			date_str: "August 2020",
			tags: ["Fire Emblem", "Severa", "Male Morgan", "Sevimorgan"],
			hidden: false
		},	
		{
			src: ["https://cdn.imgchest.com/files/6d7702a670bb.png"],
			thumbnail: "https://cdn.imgchest.com/files/e653b68b2e89.png",
			title: "Len's Biggest Fan",
			artist: "MissDash",
			artist_url: "https://bsky.app/profile/missdash.bsky.social",
			desc: "Done as a request for CYL10. MMJ Kaito would absolutely have this fan of MMJ Len, haha.",
			date_str: "February 2026",
			tags: ["Vocaloid", "KAITO", "Kagamine Len", "KaiLen"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/36165dae0109.png"],
			thumbnail: "https://cdn.imgchest.com/files/b49b80ce57c4.png",
			title: "Ebi Jail",
			artist: "Waaaaven",
			artist_url: "https://x.com/waaaaven?s=20",
			desc: "A commission I got after 2 grueling days of non-stop tiering for Len's World Link. Waaaaven was also right there with me in the server, listening to Hitorinbo Envy on endless loop. In the end, it was all worth it as I finished at T25.",
			date_str: "September 2025",
			tags: ["Vocaloid", "Kagamine Len"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/a8f299864a58.png"],
			thumbnail: "https://cdn.imgchest.com/files/b8a85635190b.png",
			title: "Lavie Lavie Chu~",
			artist: "Huyandere",
			artist_url: "https://x.com/huyandere",
			desc: "A commission of Elm as Lavie from the Surii song, Lavie. The overlap betwen Elm and the character in the song was too strong to ignore.",
			date_str: "October 2023",
			tags: ["Fire Emblem Heroes", "Elm", "Vocaloid"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/7b1b0790e72f.png"],
			thumbnail: "https://cdn.imgchest.com/files/7089b23c9a23.png",
			title: "Chase and Wuya Redraw",
			artist: "Marcsedano",
			artist_url: "https://www.deviantart.com/marcsedano",
			desc: "A commission of my favorite villainous duo from Xiaolin Showdown. This is actually a redraw of a scene in S3 Ep12. I was flabbergasted when I realized that Chase had his hands around Wuya's waist lmao and had to draw attention to it.",
			date_str: "May 2022",
			tags: ["Xiaolin Showdown", "Chase Young", "Wuya", "Chuya"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/4cc6292a41fb.JPG"],
			thumbnail: "https://cdn.imgchest.com/files/7441337574e8.png",
			title: "Revolutionary Boy Lorenz",
			artist: "micstheMD",
			artist_url: "https://x.com/micstheMD?s=20",
			desc: "This was actually a 'gift' of sorts from my friend Miso as a prize for a little contest we held among our friends. Originally, I had a more ambitious idea of the 'dance' scene from the movie with pre-timeskip Dorothea and Lorenz dancing and their post-timeskip selves in the reflection of the water, but I scaled it back to fit the budget I had.",
			date_str: "September 2021",
			tags: ["Fire Emblem 3H", "Dorothea", "Lorenz", "Dororenz", "Gift"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/56105ab2cc8b.png"],
			thumbnail: "https://cdn.imgchest.com/files/56105ab2cc8b.png",
			title: "Robin Skill Issue",
			artist: "Rita",
			artist_url: "https://x.com/_anachaga",
			desc: "A gift from my friend, ZX!",
			date_str: "March 2022",
			tags: ["Fire Emblem", "Female Robin"],
			hidden: false
		},					
		{
			src: ["https://cdn.imgchest.com/files/6e57cf4cfd2b.png"],
			thumbnail: "https://cdn.imgchest.com/files/838c55c9d4c3.png",
			title: "Summer Chrobin and Robin",
			artist: "Siren",
			artist_url: "https://x.com/ladylawga",
			desc: "A birthday gift from my friend, Silent. A cute scene of Chrom and Robin enjoying their beach date.",
			date_str: "September 2020",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin", "Gift"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/56d5c7dfaccd.png"],
			thumbnail: "https://cdn.imgchest.com/files/4aaeb05af7eb.png",
			title: "Family Outing",			
			artist: "Siren",
			artist_url: "https://x.com/ladylawga",
			desc: "A birthday gift from my friend, Silent. While Chrom and Robin are enjoying their moment of peace, Morgan is causing a bit of chaos for his sister in the background.",
			date_str: "September 2022",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Lucina", "Male Morgan", "Exalt Family", "Gift"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/c5b5268b89cc.png"],
			thumbnail: "https://cdn.imgchest.com/files/69349c5dce36.png",
			title: "Birthday Comic",
			artist: "Siren",
			artist_url: "https://x.com/ladylawga",
			desc: "A birthday gift from my friend, Silent. A fun comic that references some of my personal interests, like ballroom dancing or DDR.",
			date_str: "September 2023",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Lucina", "Male Morgan", "Exalt Family", "Gift", "Comic"],
			hidden: false
		},	
		{
			src: ["https://cdn.imgchest.com/files/3e7b1d2017c8.png"],
			thumbnail: "https://cdn.imgchest.com/files/6eb9e9ee6aed.png",
			title: "Dorothea and Lorenz",
			artist: "Siren",
			artist_url: "https://x.com/ladylawga",
			desc: "A birthday gift from my friend, Silent. As a funny backstory, I used to refer to this ship as Lorenzthea, which was misinterpreted as Lorenz and Lysithea. So when I received a fully colored illustration of Lorenz and Lysithea, I was very confused. Thankfully, Siren was gracious enough to do a quick re-do. From there onwards, I call the ship Dororenz instead haha.",
			date_str: "September 2021",
			tags: ["Fire Emblem 3H", "Dorothea", "Lorenz", "Dororenz", "Gift"],
			hidden: false
		}
	]
};
