var data = {
	images: [
		{
			src: [""],
			thumbnail: "",
			title: "Placeholder Entry",
			artist: "Placeholder Entry",
			artist_url: null,
			desc: "Do not delete this. You can use this to set the order the tags show up in the dropdown.",
			date_str: "Beginning of Time",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Lucina", "Male Morgan", "Inigo", "Severa", "Male Robin", "Sumia", "Cynthia", "Female Morgan", "Owain", "Gerome", "Virion", "Olivia", "Gaius", "Cordelia", "Vaike", "Lissa", "Frederick", "Cherche", "Soleil", "Caeldori", "Ophelia", "Damien", "Chrobin", "Exalt Family", "Lucinigo", "Sevimorgan", "Robmia", "Violet Family", "Owainthia", "Geromorgan", "Viriolivia", "Gaiusdelia", "Vaikessa", "Chercherick", "Roleswap AU", "Modern AU", "Vocaloid", "Kagamine Len", "KAITO", "Kailen", "Request", "Gift", "Collab"],
			hidden: true
		},		
		{
			src: [""],
			thumbnail: "",
			title: "",
			artist: "",
			artist_url: "",
			desc: "",
			date_str: "",
			tags: [""],
			hidden: true
		},			
		{
			src: ["https://cdn.imgchest.com/files/759631e10f42.png"],
			thumbnail: "https://cdn.imgchest.com/files/154fc82e3f8b.png",
			title: "Ylissean Queen Robin Icon",
			artist: "FlamingoPunch",
			artist_url: "https://x.com/flamingopunch",
			desc: "An icon commission of my Ylissean Queen Robin design. Irises were selected for the floral background because of the Japanese name for Ylisse being 'Iris.'",
			date_str: "May 2026",
			tags: ["Fire Emblem", "Female Robin"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/5c238a549fae.png"],
			thumbnail: "https://cdn.imgchest.com/files/34b90f866ace.png",
			title: "Summer Shadows Robin",
			artist: "Anander",
			artist_url: "https://bsky.app/profile/anander.bsky.social",
			desc: "A request I made of Anander for Shadows Robin. While looking up references, he also saw Summer Robin's design and decided to combine the two together.",
			date_str: "April 2026",
			tags: ["Fire Emblem", "Female Robin", "Request"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/6f356f2c8fc5.png"],
			thumbnail: "https://cdn.imgchest.com/files/6a4bbafb1293.png",
			title: "Morgan Doodle",
			artist: "OZ",
			artist_url: "https://x.com/oznooekaki",
			desc: "A request I made for a doodle of Male Morgan. The date on this is actually not accurate, but I wanted to keep all the requests together.",
			date_str: "April 2026",
			tags: ["Fire Emblem", "Male Morgan", "Request"],
			hidden: false
		},								
		{
			src: ["https://cdn.imgchest.com/files/60a0a3d9d3a2.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/e9f7c46e17dc.png",
			title: "Severa Doodle",
			artist: "OZ",
			artist_url: "https://x.com/oznooekaki",
			desc: "A request that Lamprey made for a doodle of Severa, to match with MOrgan.",
			date_str: "April 2026",
			tags: ["Fire Emblem", "Severa", "Request"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/68b72d679724.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/7f8d67318acd.png",
			title: "Robin Doodle",
			artist: "OZ",
			artist_url: "https://x.com/oznooekaki",
			desc: "A request that Lamprey made for a doodle of Female Robin. I'm glad that OZ caught the detail of the braids on Robin's hair!",
			date_str: "April 2026",
			tags: ["Fire Emblem", "Female Robin", "Request"],
			hidden: false
		},	
		{
			src: ["https://cdn.imgchest.com/files/441137de1353.png"],
			thumbnail: "https://cdn.imgchest.com/files/805425a38546.png",
			title: "Chrom Doodle",
			artist: "OZ",
			artist_url: "https://x.com/oznooekaki",
			desc: "A request that I made for a doodle of Chrom to match with Robin.",
			date_str: "April 2026",
			tags: ["Fire Emblem", "Chrom", "Request"],
			hidden: false
		},	
		{
			src: ["https://cdn.imgchest.com/files/91b84ccd6a93.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/b67b4863fb63.png",
			title: "Inigo Doodle",
			artist: "OZ",
			artist_url: "https://x.com/oznooekaki",
			desc: "A request that I made for a doodle of Inigo, since Lamprey and I figured we might as well round out the group.",
			date_str: "April 2026",
			tags: ["Fire Emblem", "Inigo", "Request"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/7ea28019a09a.png"],
			thumbnail: "https://cdn.imgchest.com/files/9606dc13a0b1.png",
			title: "Lucina Doodle",
			artist: "OZ",
			artist_url: "https://x.com/oznooekaki",
			desc: "A request that Lamprey made for a doodle of Lucina. The brand was added in post by me.",
			date_str: "April 2026",
			tags: ["Fire Emblem", "Lucina", "Request"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/094484f68235.png"],
			thumbnail: "https://cdn.imgchest.com/files/f7f491283b0c.png",
			title: "Wonder Duo",
			artist: "IgniteMix",
			artist_url: "https://x.com/ignitemix",
			desc: "When this scene got animated, it really blew up everywhere, and all of the fan art really got me in the mood to get a piece referencing it as well. While they're not quite as extreme as BakuDeku, Severa and Morgan do also have a bit of that tsundere x sunshine dynamic going on which is why I found they were most fitting for this piece.",
			date_str: "April 2026",
			tags: ["Fire Emblem", "Male Morgan", "Severa", "My Hero Academia"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/bb64acdc290a.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/0d5f219c5f34.png",
			title: "Coffee Order",
			artist: "Python's Bow",
			artist_url: "https://x.com/pythons_bow/media",
			desc: "Done as a request for CYL10. Local teen discovers a new coffee addiction.",
			date_str: "March 2026",
			tags: ["Fire Emblem", "Male Morgan", "Request"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/05f08bd14bd2.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/89483ddf8bfb.png",
			title: "Chrobin Heart Hands Request",
			artist: "Evomanaphy",
			artist_url: "https://x.com/EvomanaphyArt",
			desc: "Done as a request for CYL10. Combined my request with Lamprey's to have Chrom and Robin do heart hands.",
			date_str: "February 2026",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin", "Request"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/4bd09c88d804.png"],
			thumbnail: "https://cdn.imgchest.com/files/35c1ee23e6d4.png",
			title: "Kozaki-style Brave Robin",
			artist: "PeacefulandFlat",
			artist_url: "https://x.com/peacefulandflat",
			desc: "As much as I adore Wada Sachiko's art, I do wish we had gotten a full body female Robin art from Kozaki. Thus, I commissioned PeacefulandFlat to emulate Kozaki's style so we could get a peek at what could have been. Pose is a reference to Katarina's Awakening art.",
			date_str: "February 2026",
			tags: ["Fire Emblem", "Female Robin"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/c2aee1225c27.png", "https://cdn.imgchest.com/files/8dfe02a18240.png"],
			thumbnail: "https://cdn.imgchest.com/files/047e8bcbdb71.png",
			title: "Resplendent Lucina with White Hair",
			artist: "Capt Carrotcake",
			artist_url: "https://x.com/CaptCarrotCake",
			desc: "Done as a request for CYL10. White hair really goes well with her color palette for her resplendent outfit.",
			date_str: "January 2026",
			tags: ["Fire Emblem", "Lucina", "Request"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/cfc38a289e46.jpg", "https://cdn.imgchest.com/files/ef80a58c1459.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/982130f1fbe2.png",
			title: "Resplendent Male Morgan (and Lucina)",
			artist: "Alterigo60",
			artist_url: "https://bsky.app/profile/alterigo06.bsky.social",
			desc: "Done as a request for CYL10. Done in conjunction with Lamprey, as he requested resplendent Brave Lucina and I requested resplendent male Morgan.",
			date_str: "January 2026",
			tags: ["Fire Emblem", "Male Morgan", "Lucina", "Exalt Family", "Request", "Collab"],
			hidden: false
		},					
		{
			src: ["https://cdn.imgchest.com/files/e27e41e6cf42.png"],
			thumbnail: "https://cdn.imgchest.com/files/d7d6122917c8.png",
			title: "Grima and RKC Request",
			artist: "Hullu",
			artist_url: "https://x.com/hulluzola",
			desc: "Done as a request for CYL10. I love the small smirk that Grima is giving Chrom.",
			date_str: "January 2026",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Grima", "Chrobin", "Request"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/30be445e3e11.png"],
			thumbnail: "https://cdn.imgchest.com/files/79207c32f653.png",
			title: "Naga-ified Chrom",
			artist: "Kyouga",
			artist_url: "https://x.com/Kyouga05",
			desc: "My design for a Chrom with Naga's dragon features. I elected to use horns and wings that Tiki/Nowi/Nah have over the one that Naga has just because I like the look of them better.",
			date_str: "January 2026",
			tags: ["Fire Emblem", "Chrom", "Roleswap AU"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/632acbef8e48.png"],
			thumbnail: "https://cdn.imgchest.com/files/8ee2a5242231.png",
			title: "Morgan's First Kiss",
			artist: "Huyandere",
			artist_url: "https://x.com/huyandere",
			desc: "A gift for my boyfriend. This is a parody of the episode, 'Megan's First Kiss' from Drake and Josh. Gerome's casual outfit was based on my previous comm, while Morgan's casual outfit takes some inspiration from olivinearc's cardigan designs.",
			date_str: "December 2025",
			tags: ["Fire Emblem", "Female Morgan", "Gerome", "Cynthia", "Severa", "Geromorgan", "Drake and Josh"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/2b601c441378.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/0361e8cd382b.png",
			title: "Mutual Disdain",
			artist: "Yun",
			artist_url: "https://x.com/YunAfezeria",
			desc: "A piece depicting the disdain that Risen King Chrom and Ascended Queen Robin have for one another. Robin views him as Grima's mad dog, while Chrom thinks she's nothing more than Naga's puppet. Both think the other is in the more pitable situation, but know deep down inside that they're throwing rocks from a glass window.",
			date_str: "December 2025",
			tags: ["Fire Emblem", "Chrom", "Robin", "Chrobin", "Roleswap AU"],
			hidden: false
		},						
		{
			src: ["https://cdn.imgchest.com/files/5648e5cc306b.png"],
			thumbnail: "https://cdn.imgchest.com/files/1ee84b4e5be6.png",
			title: "Found You",
			artist: "aiueOKOSO",
			artist_url: "https://x.com/aiueOKOSO",
			desc: "A what-if scenario in Askr where Validar encounters the 'vessel' that had escaped from him all those years ago. But with Chrom at her side and Lucina at his back, Validar won't be getting his way.",
			date_str: "July 2025",
			tags: ["Fire Emblem", "Validar", "Chrom", "Female Robin", "Lucina", "Exalt Family"],
			hidden: false
		},					
		{
			src: ["https://cdn.imgchest.com/files/e38f05d46308.png"],
			thumbnail: "https://cdn.imgchest.com/files/87c7456b23c2.png",
			title: "Violet Family Picnic",
			artist: "ArayaEjiri",
			artist_url: "https://x.com/ArayaEjiri",
			desc: "A scene of the Violet family enjoying a family picnic.",
			date_str: "May 2025",
			tags: ["Fire Emblem", "Male Morgan", "Sumia", "Cynthia", "Female Morgan", "Owain", "Gerome", "Ophelia", "Damien", "Violet Family", "Owanthia", "Geromorgan"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/1625ec55b1dc.jpeg"],
			thumbnail: "https://cdn.imgchest.com/files/db3d26e726ed.png",
			title: "Easter Chrom and Lucina",
			artist: "Hunnymz",
			artist_url: "https://x.com/hunnymzdraws",
			desc: "Since her mother couldn't join the festivities, Lucina is excited to show off the egg that she painted in her honor. Meant to be a companion to the Halloween piece.",
			date_str: "April 2025",
			tags: ["Fire Emblem", "Chrom", "Lucina", "Female Robin", "Exalt Family"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/2474215042bf.png"],
			thumbnail: "https://cdn.imgchest.com/files/6c9baa459ebc.png",
			title: "Returning to the Past",
			artist: "Project Tiger",
			artist_url: "https://bsky.app/profile/projecttiger.bsky.social",
			desc: "The first piece showing Morgan and Lucina's role in this AU. I envision this as the moment that Morgan resolved to travel back in time in an attempt to change his fate. Since his brands are easily hidden by his gloves, I envision the only other thing that he tries to cover up is his hair color, as it is a dead giveaway of his relation to Chrom. And Lucina here is in her Great Lord class, with Geirskögul as her weapon of choice.",
			date_str: "February 2025",
			tags: ["Fire Emblem", "Male Morgan", "Lucina", "Exalt Family", "Roleswap AU"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/25fe1a55c468.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/d2a5cb726639.png",
			title: "Resplendent Female Morgan Request",
			artist: "ElpisofHope",
			artist_url: "https://x.com/Elpis0fh0pe",
			desc: "Done as a request for CYL9. This was around the time that female Morgan's resplendent design had been announced, so it was mainly on my mind, lol. This was mostly a request for my boyfriend, as I asked for brown hair and glasses as per his headcanons.",
			date_str: "January 2025",
			tags: ["Fire Emblem", "Female Morgan", "Request"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/be8ed502b8a6.jpg", "https://cdn.imgchest.com/files/868aba1cce54.jpg", "https://cdn.imgchest.com/files/d79aa607f0d3.jpg", "https://cdn.imgchest.com/files/2d3aea7affa1.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/07513f4bf1d1.png",
			title: "Victory Screen Request",
			artist: "Nysus",
			artist_url: "https://x.com/knightofgoetia",
			desc: "Done as a request for CYL9. Exalted Chrom and Grandmaster Robin are posed like the Smash victory screen. Nysus also provided quite a few angles, which was a nice surprise!",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin", "Request"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/941171f9e92c.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/da33bf638ee1.png",
			title: "Cipher Redraw",
			artist: "Ailheim",
			artist_url: "https://x.com/Ailheim",
			desc: "A redraw of that one cipher card with Grima and Chrom. The Risen in the background are also reimagined as the 'Ascendeds', which I envision as corpses that are so perfect that it's near uncanny.",
			date_str: "January 2025",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Naga", "Chrobin", "Roleswap AU"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/cdaf656a19a2.png"],
			thumbnail: "https://cdn.imgchest.com/files/0bca019e1ab0.png",
			title: "Young Chrobin Request",
			artist: "Liz",
			artist_url: "https://x.com/LizSbbp",
			desc: "A request that my friend, Liz, did for me. They're so adorable!",
			date_str: "December 2024",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin", "Request"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/b6aec78d7548.png"],
			thumbnail: "https://cdn.imgchest.com/files/a18d463d1ece.png",
			title: "Exalt Family Christmas",
			artist: "ArayaEjiri",
			artist_url: "https://x.com/ArayaEjiri",
			desc: "A scene of the Exalt family enjoying their Christmas eve. Done in collaboration with Lamprey.",
			date_str: "December 2024",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Lucina", "Inigo", "Male Morgan", "Severa", "Caeldori", "Soleil", "Exalt Family", "Lucinigo", "Sevimorgan", "Collab"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/314e9550226a.png"],
			thumbnail: "https://cdn.imgchest.com/files/6d943cd22192.png",
			title: "A Game of Chess",
			artist: "Xia Fei",
			artist_url: "https://x.com/XiaFei97",
			desc: "An intense showdown between Naga and Grima, as channeled throught their vessels. The composition was inspired by a fanart of Izaya and Mikado drawn by the pixiv user Rem＠ZZZzzz.. (who has since deleted their works). You can feel the tension practically crackling in the air...",
			date_str: "December 2024",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Grima", "Naga", "Chrobin", "Roleswap AU"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/8f7bef716d15.jpg", "https://cdn.imgchest.com/files/8f7bef716d15.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/b0d848444969.png",
			title: "Halloween Grima and Morgan",
			artist: "Hunnymz",
			artist_url: "https://x.com/hunnymzdraws",
			desc: "Morgan is happy to get to join the festivities, but even happier to be spending time with his mother. Meant to be a companion to the Easter piece. Hunnymz also provided an alternative version, where Morgan's lollipop is even BIGGER.",
			date_str: "October 2024",
			tags: ["Fire Emblem", "Female Robin", "Grima", "Male Morgan", "Exalt Family"],
			hidden: false
		},						
		{
			src: ["https://cdn.imgchest.com/files/cef265640b1b.png"],
			thumbnail: "https://cdn.imgchest.com/files/f4b1d95457cc.png",
			title: "Campfire Dinner",
			artist: "RedKite",
			artist_url: "https://x.com/RedKite333",
			desc: "A birthday gift for my friend, Silent, but secretly it was also a gift for myself, teehee. The Muspell lords and their Hel tacticians have taken a trip to Hel and are sampling the 'local cuisine' there. While Chrom seems a little skeptical of this bear meat, Robin and Ike are digging in with gusto. As for Soren? He's had worse.",
			date_str: "October 2024",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Ike", "Soren", "Chrobin", "Ikesoren"],
			hidden: false
		},					
		{
			src: ["https://cdn.imgchest.com/files/c0e20a9fd19a.png", "https://cdn.imgchest.com/files/27737ba1d95b.png"],
			thumbnail: "https://cdn.imgchest.com/files/9e527ba23990.png",
			title: "Ascended Queen Robin",
			artist: "Kinigoni",
			artist_url: "https://bsky.app/profile/kinigoni.bsky.social",
			desc: "A piece showing off Ascended Queen Robin's full design! The outfit is a mash-up of Robin's grandmaster outfit and Emmeryn's sage outfit. And as a small touch, her glove is slightly torn to show off the Mark of Grima, similar to how Risen King Chrom's sleeve is torn to show off the Exalt Brand.",
			date_str: "August 2024",
			tags: ["Fire Emblem", "Female Robin", "Roleswap AU"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/8d2ccac787a8.png"],
			thumbnail: "https://cdn.imgchest.com/files/0b224ebc9b09.png",
			title: "Valentine's Owain and Cynthia",
			artist: "Kurumikiri",
			artist_url: "https://x.com/kurumikiri",
			desc: "A commission done for the FE Rally for Gaza. This is the first Owainthia piece I've gotten, and also the first time that I solidified my headcanon of Cynthia having purple eyes, similar to how the Morgans have purple eyes in their FEH art. She has to get something from Robin, after all (and I prefer her and Morgan having the same hair color, so eye color it is, haha). If you see purple eyes in older commissions though, that's because I edited it in post.",
			date_str: "March 2024",
			tags: ["Fire Emblem", "Owain", "Cynthia", "Owainthia"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/62b81ef61112.png"],
			thumbnail: "https://cdn.imgchest.com/files/c0a69aaabea6.png",
			title: "Order vs. Chaos",
			artist: "Daphne",
			artist_url: "https://bsky.app/profile/daphnecomics.bsky.social",
			desc: "A skeb-style piece and part of the FE Rally for Gaza. This was the very first commission that I ever got for the roleswap AU, and since it was skeb-style, there are some inconsistencies in Robin's ascended queen outfit that I ironed out with the next commission. There are also some slightly alterations that I did myself, such as the color of Naga!Chrom's coat or re-adding the black sheer around Grima!Robin's arms.",
			date_str: "March 2024",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Grima", "Naga", "Chrobin", "Roleswap AU"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/a776e2f9dce0.png", "https://cdn.imgchest.com/files/e5d6adada8d3.png"],
			thumbnail: "https://cdn.imgchest.com/files/695d2f371c2b.png",
			title: "Damien Portrait",
			artist: "Lynarc",
			artist_url: "https://x.com/CM_Lynarc",
			desc: "The first piece that I got for my Geromorgan fankid, Damien! I followed the same design principle as Fates in which most of his design is based on his father (e.g., wyvern rider, French name, red eyes). As a somewhat inverse of Selkie and Velouria, his hair would change color depending on his mother but the streak would always remain the same color. His bandana mask shares the same pattern as Cherche's headband, and his armor color scheme is based on Frederick's. He also has two pegasus hair clips on his tassel as a nod to Sumia.",
			date_str: "February 2024",
			tags: ["Fire Emblem", "Damien"],
			hidden: false
		},						
		{
			src: ["https://cdn.imgchest.com/files/ef6fa370bb85.png"],
			thumbnail: "https://cdn.imgchest.com/files/78734ff6a632.png",
			title: "Super Mario Chrobin",
			artist: "Moccha Kofii",
			artist_url: "https://x.com/moccha_kofii",
			desc: "Chrom and Robin as iconic video game couples. Because Robin's red palette gave her blonde hair, and Peach also had a red palette that gave her a red dress, those colors were used. And since we're in the realm of Smash Ultimate, Chrom Mii (whose body type more closely replicates Mario's) is here to steal Chrom's girl.",
			date_str: "February 2024",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin", "Super Mario Brothers"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/5706d10e5145.png"],
			thumbnail: "https://cdn.imgchest.com/files/f32db6474a45.png",
			title: "Legend of Chrobin",
			artist: "Moccha Kofii",
			artist_url: "https://x.com/moccha_kofii",
			desc: "Chrom and Robin as iconic video game couples. The parallels between Zelda who became a dragon in Tears of the Kingdom and Robin who becomes Grima in a bad timeline was not lost on me. It was also very easy to incorporate Chrom's brand into the design of his right arm.",
			date_str: "February 2024",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin", "Legend of Zelda"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/1a3d128f2b85.png"],
			thumbnail: "https://cdn.imgchest.com/files/fa2f9101eb79.png",
			title: "Chrobin the Hedgehogs",
			artist: "Moccha Kofii",
			artist_url: "https://x.com/moccha_kofii",
			desc: "Chrom and Robin as iconic video game couples. I was initially considering using the Sonic Boom outfits, but the Murder of Sonic was such a great game that I had to go with that one instead. I love how Moccha drew the background, giving it an incredibly stylistic slant that is just so fitting for something from the Sonic series.",
			date_str: "February 2024",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin", "Sonic the Hedgehog"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/3f1030862f45.png"],
			thumbnail: "https://cdn.imgchest.com/files/7a327e181613.png",
			title: "Dual Bloodlines",
			artist: "Neighbourh",
			artist_url: "https://x.com/yrfreakyneighbr",
			desc: "A commission depicting Fallen Morgan grappling with his two bloodlines. It was a big honor to get a commission from Neighbourh himself.",
			date_str: "June 2023",
			tags: ["Fire Emblem", "Male Morgan"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/b0fe68c3439d.jpg", "https://cdn.imgchest.com/files/918846b92cea.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/4279de011d7c.png",
			title: "Hot Springs Lucina",
			artist: "GzeiDraws",
			artist_url: "https://bsky.app/profile/gzeidraws.bsky.social",
			desc: "A gift that I got for Yoostink as a thank you for the Trujek art. Since he loves chocolate milk, I requested for Lucina to be drinking chocolate milk at the hot springs. And next to her is either a tiny wooden mother (as I love also getting gifts for myself, haha) or a tiny wooden husband.",
			date_str: "January 2023",
			tags: ["Fire Emblem", "Lucina"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/aa315f01a865.png"],
			thumbnail: "https://cdn.imgchest.com/files/b74f43de87ca.png",
			title: "Ponytail Lucina",
			artist: "micstheMD",
			artist_url: "https://x.com/micstheMD?s=20",
			desc: "A simple request I made of Lucina in a ponytail and Robin's undershirt.",
			date_str: "January 2023",
			tags: ["Fire Emblem", "Lucina", "Request"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/47579acaf4bf.png"],
			thumbnail: "https://cdn.imgchest.com/files/b2adb1e9c56f.png",
			title: "Day of Devotion",
			artist: "Fujikawa Akira",
			artist_url: "https://x.com/a_fjkw",
			desc: "I'm still in awe that I was able to get a commission from an actual FEH artist, and Fujikawa Akira no less. An absolutely gorgeous and breathtaking piece showing Valentine's Chrom and Robin enjoying themselves at the festival. Basically my profile picture on all socials (bar tumblr).",
			date_str: "January 2023",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/9e0a7a00fe59.png"],
			thumbnail: "https://cdn.imgchest.com/files/f35da9e72eea.png",
			title: "Exalt Family as the AskrEmbla Family",
			artist: "Yorey",
			artist_url: "https://x.com/_yorey_",
			desc: "Evil white-haired deity falls for a divine blue-haired himbo? More likely than you think. Had to combine my two favorite FE families together since their parallels are too obvious to ignore.",
			date_str: "December 2022",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Lucina", "Male Morgan", "Exalt Family"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/43f287cbdb38.png"],
			thumbnail: "https://cdn.imgchest.com/files/f2cc7cc28ed7.png",
			title: "The Shepherd",
			artist: "Phe",
			artist_url: "https://x.com/almostphe",
			desc: "Given that Chrom is the captain of the Shepherds, it only felt fitting to cross him over with my other favorite Shepherd. And of course, Robin also here as the adorable Mikleo plush riding along on his shoulder.",
			date_str: "December 2022",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin", "Tales of Zestiria"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/d732b9458321.png"],
			thumbnail: "https://cdn.imgchest.com/files/72e97c43de71.png",
			title: "Chrobin as Bubbline",
			artist: "Yannurs (formerly AcrylicStroke)",
			artist_url: "https://x.com/yannurs_",
			desc: "A commission of Chrom and Robin as Marshall Lee and Princess Bubblegum. The labcoat and pink turtleneck really suit Robin, in my opinion.",
			date_str: "July 2022",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin", "Adventure Time"],
			hidden: false
		},						
		{
			src: ["https://cdn.imgchest.com/files/ad0509ba447a.png"],
			thumbnail: "https://cdn.imgchest.com/files/ef54e974bced.png",
			title: "With Grandpa Validar",
			artist: "Trunswicked",
			artist_url: "https://bsky.app/profile/trunswicked.bsky.social",
			desc: "A YCH commission. It's meant to be your FEH team with your summoner in the center, but I opted for Validar and his grandchildren instead. All of them have a weapon with some sort of Plegian effect in them, courtesy of grandpa's influence (lol).",
			date_str: "June 2022",
			tags: ["Fire Emblem", "Validar", "Lucina", "Cynthia", "Male Morgan", "Female Morgan", "Exalt Family", "Violet Family"],
			hidden: false
		},						
		{
			src: ["https://cdn.imgchest.com/files/d8659019793f.png"],
			thumbnail: "https://cdn.imgchest.com/files/154444066f86.png",
			title: "Submit to Grima",
			artist: "Squiddlybopbop",
			artist_url: "https://x.com/squiddlybopbop",
			desc: "This piece had was actually already in the works by Squiddly but was going to just remain an uncompleted WIP until I paid for it to be finished. I love the Ursula-like vibes that Grima has, and the gorgeous paint style. Definitely the most unconventional 'commission' I've ever done.",
			date_str: "May 2022",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Grima", "Chrobin"],
			hidden: false
		},					
		{
			src: ["https://cdn.imgchest.com/files/84805b23c3d7.png"],
			thumbnail: "https://cdn.imgchest.com/files/a14acb2dc136.png",
			title: "Father's Day",
			artist: "NicoTopin",
			artist_url: "https://x.com/Nico_squitter",
			desc: "A piece celebrating Father's Day, featuring Chrom and his son (and his son but going through a rebellious phase).",
			date_str: "June 2022",
			tags: ["Fire Emblem", "Chrom", "Male Morgan", "Exalt Family"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/6b3b8e363c53.png"],
			thumbnail: "https://cdn.imgchest.com/files/2103b06c1e39.png",
			title: "Mother's Day",
			artist: "NicoTopin",
			artist_url: "https://x.com/Nico_squitter",
			desc: "A piece celebrating Mother's Day, featuring Lucina and her mom (and her mom but evil).",
			date_str: "May 2022",
			tags: ["Fire Emblem", "Female Robin", "Lucina", "Grima", "Exalt Family"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/8ca8e87329cd.png"],
			thumbnail: "https://cdn.imgchest.com/files/cf70e54028bc.png",
			title: "Weapon Refinery",
			artist: "Mnejing",
			artist_url: "https://x.com/Mnejing30",
			desc: "A Patreon request for a sketch of Lucina and Morgan celebrating their weapon refines. I wanted to highlight that both of them share a Plegian effect, which is just more fuel for my Chrobin agenda, haha.",
			date_str: "March 2022",
			tags: ["Fire Emblem", "Lucina", "Male Morgan", "Exalt Family"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/944c740bb7bc.JPG", "https://cdn.imgchest.com/files/eac6dd472d7d.JPG"],
			thumbnail: "https://cdn.imgchest.com/files/9c03a2dd890d.png",
			title: "Sweet Dreams",
			artist: "micstheMD",
			artist_url: "https://x.com/micstheMD?s=20",
			desc: "Lucina is sleeping peacefully on her mother's lap. But there seems to be something a little... off about this scene.",
			date_str: "February 2022",
			tags: ["Fire Emblem", "Female Robin", "Grima", "Lucina", "Exalt Family"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/e38563fbecda.png", "https://cdn.imgchest.com/files/f8ef8812316e.png"],
			thumbnail: "https://cdn.imgchest.com/files/2b0e1d15b74f.png",
			title: "Heaven and Hell",
			artist: "Shugo",
			artist_url: "https://x.com/hiomaika",
			desc: "While Valentine’s Robin has found herself unexpectedly swept off her feet by this intimidating (yet oddly gentle) stranger, Valentine’s Chrom has his hands full dealing with this sly demon trying to whisper temptations in his ears. Which do you prefer: heaven or hell?",
			date_str: "February 2022",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Grima", "Chrobin"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/06e3db1ba200.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/4c6bc9de52e2.png",
			title: "Valentine's Lucina and Robin",
			artist: "Blof_404",
			artist_url: null,
			desc: "A commission of Lucina and Robin enjoying the Day of Devotion. Since Morgan couldn't make it, Lucina very thoughtfully prepared a souvenir to bring back for him. Background, which is a FEH asset, was added by me.",
			date_str: "February 2022",
			tags: ["Fire Emblem", "Female Robin", "Lucina", "Exalt Family"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/888088c23a6e.png"],
			thumbnail: "https://cdn.imgchest.com/files/2f270ce1a228.png",
			title: "Ice Dancing",
			artist: "ItsToast",
			artist_url: "https://x.com/oreocorio",
			desc: "I always adored the ballroom dancing that Virion and Olivia did in their support, and I feel like that would also naturally translate over to ice dancing. They would get 10's across the board, in my humble opinion.",
			date_str: "February 2022",
			tags: ["Fire Emblem", "Virion", "Olivia", "Viriolivia"],
			hidden: false
		},						
		{
			src: ["https://cdn.imgchest.com/files/3c8fd4d04c5a.png"],
			thumbnail: "https://cdn.imgchest.com/files/942c6261092b.png",
			title: "CNY Robin",
			artist: "B_PearlWhite",
			artist_url: "https://x.com/B_PearlWhite",
			desc: "Grah, I LOVE putting my favorite characters in my cultural clothing! Robin is celebrating Chinese New Year in style, with Grima as the Chinese dragon. And in the background, instead of the character for fortune (福), I had the Japanese characters for the Chrobin ship name (クロルフ). I had actually marked this Skeb to be private because I wanted to wait until Chinese New Year to post it, but then B_PearlWhite had posted it to their Twitter anyways lol. I don't care, I'm marking the date as February anyways!",
			date_str: "February 2022",
			tags: ["Fire Emblem", "Female Robin"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/df8f198bc12e.png"],
			thumbnail: "https://cdn.imgchest.com/files/5f5c2afc566c.png",
			title: "Chrom - Prince",
			artist: "camiCR",
			artist_url: "https://x.com/camilitroxCR",
			desc: "An emote of Chrom extending his hand in a princely manner. Pairs with the female Robin one",
			date_str: "January 2022",
			tags: ["Fire Emblem", "Chrom"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/321547aca5e8.png"],
			thumbnail: "https://cdn.imgchest.com/files/321547aca5e8.png",
			title: "F!Robin - Wow",
			artist: "camiCR",
			artist_url: "https://x.com/camilitroxCR",
			desc: "An emote of Robin swooning over something. Pairs with the Chrom one.",
			date_str: "January 2022",
			tags: ["Fire Emblem", "Female Robin"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/8c8451a7773a.png"],
			thumbnail: "https://cdn.imgchest.com/files/8c8451a7773a.png",
			title: "Lucina - Disapproval",
			artist: "camiCR",
			artist_url: "https://x.com/camilitroxCR",
			desc: "An emote of Lucina giving a thumbs down. Pairs with the male Morgan one. (I only just now noticed that Lucina is missing her brand as well, lol, so I manually added it myself.)",
			date_str: "January 2022",
			tags: ["Fire Emblem", "Lucina"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/cfbb29529a8d.png"],
			thumbnail: "https://cdn.imgchest.com/files/cfbb29529a8d.png",
			title: "M!Morgan - Approval",
			artist: "camiCR",
			artist_url: "https://x.com/camilitroxCR",
			desc: "An emote of Morgan giving a thumbs up. Pairs with the Lucina one.",
			date_str: "January 2022",
			tags: ["Fire Emblem", "Male Morgan"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/90a79dc6426b.png","https://cdn.imgchest.com/files/bd01b9c576ba.png"],
			thumbnail: "https://cdn.imgchest.com/files/90a79dc6426b.png",
			title: "Cynthia - Excited",
			artist: "camiCR",
			artist_url: "https://x.com/camilitroxCR",
			desc: "An emote of Cynthia being excited. This is a reference to a Luffy expression, as requested by my boyfriend. One version is my headcanon of her as having brown hair and the other version is his headcanon of her having purple hair.",
			date_str: "January 2022",
			tags: ["Fire Emblem", "Cynthia"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/b9e20f600f5c.png"],
			thumbnail: "https://cdn.imgchest.com/files/b9e20f600f5c.png",
			title: "F!Morgan - Sour",
			artist: "camiCR",
			artist_url: "https://x.com/camilitroxCR",
			desc: "An emote of Morgan making a sour face. This is a reference to a Luffy expression, as requested by my boyfriend.",
			date_str: "January 2022",
			tags: ["Fire Emblem", "Female Morgan"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/e73c55f4ef3e.png"],
			thumbnail: "https://cdn.imgchest.com/files/65f66505f6e5.png",
			title: "Nifl Robin and Muspell Chrom",
			artist: "DrawingDDoom",
			artist_url: "https://bsky.app/profile/drawingddoom.bsky.social",
			desc: "This was a piece that I had commissioned before we got Robin's actual resplendent design. At the time, I was hoping for a Nifl design to match with Chrom's Muspell design. While I would still have preferred that, I can't be mad since there was a point that I expected to not even get a resplendent at all, lol. And Brave Robin brought the ice veins so I was slightly vindicated in some ways, haha.",
			date_str: "January 2022",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin"],
			hidden: false
		},						
		{
			src: ["https://cdn.imgchest.com/files/77ed2497832d.png", "https://cdn.imgchest.com/files/36fc473fc84f.png", "https://cdn.imgchest.com/files/86a94f3426d8.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/9256509a0e5e.png",
			title: "Ready Steady",
			artist: "Katarina_Neko",
			artist_url: "https://x.com/katarina_neko",
			desc: "A commission of Chrom, Robin, and Lucina dressed as Len, Miku, and Rin from the song 'Ready Steady.' Although the Mark of Grima is on the opposite shoulder that I normally headcanon it as, I decided it was fine since I still wanted to show it off. Also featuring Morgan as GigaP, haha. Kat also kindly included a bonus of Morgan as the cameraman.",
			date_str: "January 2022",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Lucina", "Male Morgan", "Exalt Family", "Vocaloid"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/8f4d38c6e9e0.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/02aac6e7ef3a.png",
			title: "Geromorgan as AyaHina",
			artist: "Astral / Asu",
			artist_url: "https://x.com/AstralBlooming?s=20",
			desc: "When commissioning a crossover with another series, I usually pick my absolute favorite characters from that series, but I made an exception here because I thought Ayato and Hinami would best suit Gerome and Morgan. I find it fun that Gerome is still wearing a mask, but only for the lower half of his face now.",
			date_str: "January 2022",
			tags: ["Fire Emblem", "Gerome", "Female Morgan", "Geromorgan", "Tokyo Ghoul"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/106b6a1d5b51.png"],
			thumbnail: "https://cdn.imgchest.com/files/6a6b385d424e.png",
			title: "Ylissean King Morgan and Plegian Queen Lucina",
			artist: "LazzleDazzle",
			artist_url: "https://bsky.app/profile/lazzledazzle.bsky.social",
			desc: "A commission of Ylissean King Morgan and Plegian Queen Lucina (background added by me). This was probably the first piece I got with the Mark of Grima on Lucina's shoulder. Fun fact, the tumblr user gurinderstehara actually commissioned theblindarcher for GBA-styled sprites based on this piece.",
			date_str: "January 2022",
			tags: ["Fire Emblem", "Lucina", "Male Morgan", "Exalt Family"],
			hidden: false
		},						
		{
			src: ["https://cdn.imgchest.com/files/955e915a9a54.png", "https://cdn.imgchest.com/files/51255534d108.png"],
			thumbnail: "https://cdn.imgchest.com/files/c4bfe602d6be.png",
			title: "Objection!",
			artist: "Dinzeeyz",
			artist_url: "https://x.com/d1nnple",
			desc: "A commission of Lucina, Morgan, and Inigo as Apollo, Trucy, and Klavier respectively. I only realized too late that I should have had Inigo call Lucina 'Fraulein Frowny' instead, lol.",
			date_str: "December 2021",
			tags: ["Fire Emblem", "Lucina", "Male Morgan", "Inigo", "Exalt Family", "Lucinigo", "Ace Attorney"],
			hidden: false
		},					
		{
			src: ["https://cdn.imgchest.com/files/2bc4246b5848.png"],
			thumbnail: "https://cdn.imgchest.com/files/a7bd0915b6f2.png",
			title: "I say 'Vol,' you say 'Tron!'",
			artist: "RedKite",
			artist_url: "https://x.com/RedKite333",
			desc: "A commission of the Gen2 kids dressed as the Voltron pilots and doing the Haruhi pose. I also mainly chose the colors based on my own preferences (e.g., Owainthia as Klance, the blueberry siblings as Shiro and Pidge, etc.).",
			date_str: "November 2021",
			tags: ["Fire Emblem", "Lucina", "Owain", "Cynthia", "Male Morgan", "Female Morgan", "Voltron the Legendary Defender"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/70297827dd06.jpeg"],
			thumbnail: "https://cdn.imgchest.com/files/0b4333ff627d.png",
			title: "Male Morgan Request",
			artist: "t_misaomaru",
			artist_url: "https://x.com/t_misaomaru",
			desc: "A request done for me by t_misaomaru. Since it was a request, I didn't specify brown eyes for Morgan, but he looks really cute with blue eyes too.",
			date_str: "November 2021",
			tags: ["Fire Emblem", "Male Morgan", "Request"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/11f1d43f2322.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/a88c96e84f03.png",
			title: "Fashion runs in the family",
			artist: "FabiZetha",
			artist_url: "https://x.com/FabiZetha",
			desc: "A silly little comic pointing out how Vaike, Owain, and Ophelia all basically have their chests out. Poor Lissa is the only one with any sense of decency in the family.",
			date_str: "October 2021",
			tags: ["Fire Emblem", "Vaike", "Lissa", "Owain", "Ophelia", "Vaikessa", "Comic"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/dfb5ec8f07eb.png"],
			thumbnail: "https://cdn.imgchest.com/files/3cea0487d647.png",
			title: "Sevimorgan as Joshtelle",
			artist: "Inkanii",
			artist_url: "https://x.com/inkanii",
			desc: "A commission of Severa and Morgan as Estelle and Joshua. Beyond the visual similarities, the windmill scene where Estelle has Joshua feed her reminded me of Severa and Morgan's support, which is why I wanted to reference that with this piece. Although in this case, Severa is the one doing the feeding instead, haha.",
			date_str: "",
			tags: ["Fire Emblem", "Male Morgan", "Severa", "Sevimorgan", "Trails in the Sky"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/4a7ebf224a96.PNG"],
			thumbnail: "https://cdn.imgchest.com/files/7fad4b68a503.png",
			title: "Tea Time with Grandma",
			artist: "MiddleTide",
			artist_url: "https://x.com/middletide_art",
			desc: "A commission of grandma Robin enjoying tea time with her two favorite grandchildren. In the background is a painting based on one of Middletide's own artworks, which is a fun touch.",
			date_str: "October 2021",
			tags: ["Fire Emblem", "Female Robin", "Caeldori", "Soleil", "Exalt Family"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/abb3e5b59f0f.png", "https://cdn.imgchest.com/files/27258f91813c.png"],
			thumbnail: "https://cdn.imgchest.com/files/bc0e5ce4d7b9.png",
			title: "Keyblader Wielder Lucina",
			artist: "Apticho",
			artist_url: "https://bsky.app/profile/apticho.bsky.social",
			desc: "Lucina's design was one that Apticho had already designed on their own, and one that I liked a lot so I went straight to the source to get a commission. Oblivion and Oathkeeper are my absolute favorite keyblades so I wanted Lucina to wield those as well. They have a bit of custom flair to them with the addition of the Mark of Grima and Exalted Brand, as well as the swap from the paopu fruit to an orange and the crown to Tactical Gale. Included is also a 'nort version, since it's almost as if Lucina inherited Robin's hair and color.",
			date_str: "September 2021",
			tags: ["Fire Emblem", "Lucina", "Kingdom Hearts"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/2bbfa35767a0.png"],
			thumbnail: "https://cdn.imgchest.com/files/5cfb733ce3c3.png",
			title: "Lucina and Morgan as the Brief siblings",
			artist: "Nosoiquio",
			artist_url: "https://x.com/nosoiquio",
			desc: "Given the obvious parallels between Lucina and Trunks, it only felt fitting to pay homage to two of my favorite characters. And naturally, Morgan had to join his sister. It was an interesting challenge to design a male version of Bulla's outfit that would still be recognizable as hers, considering someone else would be wearing it, but I think I did a good job.",
			date_str: "September 2021",
			tags: ["Fire Emblem", "Lucina", "Male Morgan", "Exalt Family", "Dragonball Z"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/5eb772bfcbda.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/e19e90a58ec7.png",
			title: "The King of Plegia and Queen of Ylisse",
			artist: "Picnicic",
			artist_url: "https://x.com/picnicic",
			desc: "A skeb-style commission in which Chrom was born Plegian and Robin was born Ylissean. It was fun to reimagine where their brands would be in this scenario. The background also never ceases to take my breath away.",
			date_str: "August 2021",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/0720edc532b5.png"],
			thumbnail: "https://cdn.imgchest.com/files/8d2c09898d43.png",
			title: "Imitation Black Chrobin",
			artist: "HaruAki",
			artist_url: "https://x.com/scl_HaruAki",
			desc: "As a major Vanan'Ice fan, it was a dream come true to get to see Chrom and Robin drawn by the HaruAki, especially since I was unsure if she would take non-OC requests. Naturally, I had to request them dressed as Kaito and Len from 'IMITATION Black,' as who else would know these outfits better than HaruAki herself? Definitely one of my absolute favorite commissions ever.",
			date_str: "July 2021",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin", "Vocaloid"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/627af6568ee9.png"],
			thumbnail: "https://cdn.imgchest.com/files/c539a4b0718e.png",
			title: "Mother's Pendant",
			artist: "Yunah",
			artist_url: "https://x.com/LordYunaa",
			desc: "When I saw that Summer Robin had a necklace, my mind immediately went to the pendant that Lucina mentioned receiving from her mother in her Gerome supports. And of course, I had to headcanon around this.",
			date_str: "July 2021",
			tags: ["Fire Emblem", "Female Robin", "Lucina", "Exalt Family"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/840da7eb85c5.png"],
			thumbnail: "https://cdn.imgchest.com/files/574a7f6987f8.png",
			title: "",
			artist: "Liz",
			artist_url: "https://x.com/LizSbbp",
			desc: "A request that my friend, Liz, did for me years ago. I don't actually remember the exact date was, so I'm just guess-timating.",
			date_str: "June 2021",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Male Morgan", "Exalt Family", "Request"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/deebbdd822e8.png"],
			thumbnail: "https://cdn.imgchest.com/files/53a0d502e854.png",
			title: "Chrom and Morgan have achieved B-ranked support",
			artist: "natsuB_Bkoge",
			artist_url: "https://x.com/natsuB_Bkoge",
			desc: "An angsty piece exploring the relationship between fallen Morgan and Risen King Chrom. They're both shells of their former selves and yet... perhaps they've found some comfort in the invisible ties that still tie them together.",
			date_str: "June 2021",
			tags: ["Fire Emblem", "Chrom", "Male Morgan", "Exalt Family"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/3f62056e63b3.png"],
			thumbnail: "https://cdn.imgchest.com/files/bbf05808f341.png",
			title: "Box Art",
			artist: "SnipperPool",
			artist_url: "https://x.com/SnipperPool",
			desc: "A commission done by a friend, where Morgan and Owain have taken the place of their fathers on the box art. Morgan is in the Grandmaster class while Owain is in the Dread Fighter class. Background edits were done by me.",
			date_str: "May 2021",
			tags: ["Fire Emblem", "Male Morgan", "Owain"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/1bb3093d16ef.png"],
			thumbnail: "https://cdn.imgchest.com/files/c52f7f947077.png",
			title: "The Three Mask-eteers",
			artist: "Riidi",
			artist_url: "https://x.com/m_riidi",
			desc: "A commission of Inigo, Gerome, and Lucina dressed as Roy, Marcus, and Lilina respectively. A little more customization went into Lucina's outfit to reference Robin as her mother.",
			date_str: "April 2021",
			tags: ["Fire Emblem", "Inigo", "Gerome", "Lucina"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/91df7ce44b5d.png"],
			thumbnail: "https://cdn.imgchest.com/files/9693ae8fec50.png",
			title: "The New Pegasus Trio",
			artist: "Riidi",
			artist_url: "https://x.com/m_riidi",
			desc: "A commission of Cynthia, Severa, and Morgan dressed as Palla, Catria, and Est respectively.",
			date_str: "April 2021",
			tags: ["Fire Emblem", "Cynthia", "Severa", "Female Morgan"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/38401c923291.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/be1c2540adfd.png",
			title: "Ballroom Chrom and Robin",
			artist: "Erumei24",
			artist_url: "https://x.com/erumei24",
			desc: "A commission of Chrom and Robin wearing a slightly tweaked version of ballroom Sigurd and Deirdre's outfits. I've always enjoyed the parallels between these two couples, and given how much I also love ballroom dancing, this felt like a no-brainer for me to commission. For a long while, this Robin was also my profile picture on Twitter because of how much I truly adore this piece.",
			date_str: "March 2021",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/2a55bed817ed.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/d96f0c8f30b1.png",
			title: "Wedding Robin and Sumia",
			artist: "Erumei24",
			artist_url: "https://x.com/erumei24",
			desc: "A commission of Robin and Sumia wearing a slightly tweaked version of wedding Marth and Caeda's outfits.  This was a gift for my boyfriend for our anniversary. Sumia as Caeda is obvious, but Robin as Marth is a nod to his support with Tiki in which she outright compares the two and says that Robin is more like Marth than Chrom is. This is also one of my personal favorite pieces that I have ever commissioned.",
			date_str: "March 2021",
			tags: ["Fire Emblem", "Male Robin", "Sumia", "Robmia"],
			hidden: false
		},
			{
			src: ["https://cdn.imgchest.com/files/d86446cb9c0a.png"],
			thumbnail: "https://cdn.imgchest.com/files/01c79a434cd9.png",
			title: "Learning from Dad - Inigo Side",
			artist: "EdithSotoArt",
			artist_url: "https://x.com/EdithSotoArt",
			desc: "Since Lucina inherited her genius from her mother, Inigo thought to impress her by showing off his own tactical prowess. However, chess is a little harder than he expected… Thankfully, his father is a patient teacher, especially when he has his cup of tea to sip on while waiting for Inigo to make his next move.",
			date_str: "March 2021",
			tags: ["Fire Emblem", "Virion", "Inigo", "Lucina", "Viriolivia", "Lucinigo"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/f1b9e6767d6b.png"],
			thumbnail: "https://cdn.imgchest.com/files/d12741cc6e9f.png",
			title: "Learning from Dad - Severa Side",
			artist: "EdithSotoArt",
			artist_url: "https://x.com/EdithSotoArt",
			desc: "While Severa would sooner die than touch a bug, bug-themed cookies were an acceptable enough substitute. After all, the way to a person’s heart is through their stomach… or so her daddy says. And with his help, there was no way she could fail to win Morgan’s favor!",
			date_str: "March 2021",
			tags: ["Fire Emblem", "Gaius", "Cordelia", "Male Morgan", "Gaiusdelia", "Sevimorgan"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/f1ea7100c60f.png"],
			thumbnail: "https://cdn.imgchest.com/files/f1ea7100c60f.png",
			title: "Chrom - Confusion",
			artist: "Rita",
			artist_url: "https://x.com/_anachaga",
			desc: "An emote of Chrom being confused (referred to as Chromfusion). Pairs with the female Robin one.",
			date_str: "February 2021",
			tags: ["Fire Emblem", "Chrom"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/dca93862517f.png"],
			thumbnail: "https://cdn.imgchest.com/files/dca93862517f.png",
			title: "F!Robin - I See!",
			artist: "Rita",
			artist_url: "https://x.com/_anachaga",
			desc: "A emote of Robin doing the 'naruhodo!' pose. Pairs with the Chrom one.",
			date_str: "February 2021",
			tags: ["Fire Emblem", "Female Robin"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/6206c261de4d.png"],
			thumbnail: "https://cdn.imgchest.com/files/6206c261de4d.png",
			title: "Lucina - Cool Cry",
			artist: "Rita",
			artist_url: "https://x.com/_anachaga",
			desc: "An emote of Lucina with sunglasses crying while doing double fingerguns.",
			date_str: "February 2021",
			tags: ["Fire Emblem", "Lucina"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/2e5268fd9de4.png"],
			thumbnail: "https://cdn.imgchest.com/files/2e5268fd9de4.png",
			title: "M!Morgan - Smug",
			artist: "Rita",
			artist_url: "https://x.com/_anachaga",
			desc: "An emote of Morgan being smug.",
			date_str: "February 2021",
			tags: ["Fire Emblem", "Male Morgan"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/2114c03b4b16.png"],
			thumbnail: "https://cdn.imgchest.com/files/2114c03b4b16.png",
			title: "Sumia - Bashful",
			artist: "Rita",
			artist_url: "https://x.com/_anachaga",
			desc: "An emote of Sumia being bashful, as requested by my boyfriend. Pairs with the male Robin one.",
			date_str: "February 2021",
			tags: ["Fire Emblem", "Sumia"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/7f59881310e6.png"],
			thumbnail: "https://cdn.imgchest.com/files/7f59881310e6.png",
			title: "M!Robin - Sheepish",
			artist: "Rita",
			artist_url: "https://x.com/_anachaga",
			desc: "An emote of Robin laughing while embarrassed, as requested by my boyfriend. Pairs with the Sumia one.",
			date_str: "February 2021",
			tags: ["Fire Emblem", "Male Robin"],
			hidden: false
		},					
		{
			src: ["https://cdn.imgchest.com/files/5fd89d608dbc.jpeg"],
			thumbnail: "https://cdn.imgchest.com/files/e0d5192a814b.png",
			title: "New Years Chrom and Morgan",
			artist: "Vallurite",
			artist_url: "https://x.com/Vallurite?s=20",
			desc: "Chrom and Morgan are ringing in the New Year with their wonderful new kimonos. And they're not alone, as Chrom has Robin on his hagiota and Morgan has Lucina on his karuta card. Chrom and Lucina's kimonos are based on their design from the Daily Life of Heroes manga, while Morgan and Robin's are my own design. And of course, I couldn't resist giving Morgan the kagami mochi accessory for the cheeky connection to oranges.",
			date_str: "January 2021",
			tags: ["Fire Emblem", "Male Morgan", "Chrom", "Exalt Family"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/37e6483f71a0.png"],
			thumbnail: "https://cdn.imgchest.com/files/4136e13d6fda.png",
			title: "Winter Lucina and Morgan",
			artist: "Majibomber",
			artist_url: "https://x.com/majibomber",
			desc: "Celebrating Christmas with a commission of Lucina and Morgan dressed as their ancestors, Marth and Elice. Background (which is a FEH asset) was added by me! As an aside, this is a period of time where I wasn't consistent with Morgan's eye color hence the blue eyes despite my personal preference for brown eyes on him.",
			date_str: "December 2020",
			tags: ["Fire Emblem", "Lucina", "Male Morgan", "Exalt Family"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/4fae0933463d.png"],
			thumbnail: "https://cdn.imgchest.com/files/28e76c5c8006.png",
			title: "Taking After Their Parents",
			artist: "Nootnootles",
			artist_url: "https://x.com/nootnootles",
			desc: "A commission I got from a friend of mine of the Morgans taking after their parents. Male Morgan is holding Falchion while female Morgan is holding Luna. Some of the details on female Morgan are also based on my boyfriend's preferences, such as having glasses or holding a Piranha 'flower.'",
			date_str: "October 2020",
			tags: ["Fire Emblem", "Male Morgan", "Female Morgan"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/183f4a393132.png"],
			thumbnail: "https://cdn.imgchest.com/files/c91c92b1dc63.png",
			title: "Great Lord Lucina and Bow Knight Inigo",
			artist: "Lace",
			artist_url: "https://bsky.app/profile/adelleein.bsky.social",
			desc: "One of the very first commissions I ever got, which was done for a donation rally. The commission depicts my preferred final classes for Lucina and Inigo, which is Great Lord and Bow Knight respectively. The flower petals around Lucina are a reference to the skill Ignis. The bow sprite is Dignified Bow, and the sword sprite is Skuld.",
			date_str: "August 2020",
			tags: ["Fire Emblem", "Lucina", "Inigo", "Lucinigo"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/08fa2ad5fa25.png"],
			thumbnail: "https://cdn.imgchest.com/files/cff158f2e7c2.png",
			title: "Grandmaster Morgan and Dark Flier Severa",
			artist: "Lace",
			artist_url: "https://bsky.app/profile/adelleein.bsky.social",
			desc: "One of the very first commissions I ever got, which was done for a donation rally. The commission depicts my preferred final classes for Morgan and Severa, which is Grandmaster and Dark Flier respectively. The green tome sprite is Excalibur.",
			date_str: "August 2020",
			tags: ["Fire Emblem", "Severa", "Male Morgan", "Sevimorgan"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/80989f8549d0.png"],
			thumbnail: "https://cdn.imgchest.com/files/aa2871bf95df.png",
			title: "The Prince of Darkness",
			artist: "Lucas/Sun",
			artist_url: "https://x.com/ultimatesun_",
			desc: "A commission done by my friend of Len as Ralsei. As for the rest of the Fun Gang, I would pick Miku as Kris and Rin as Susie.",
			date_str: "May 2026",
			tags: ["Vocaloid", "Kagamine Len", "Deltarune"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/813cdea78d64.png", "https://cdn.imgchest.com/files/4ff392ac8b00.png"],
			thumbnail: "https://cdn.imgchest.com/files/4f2c1cb25400.png",
			title: "Pombon and Litten",
			artist: "Melt/Ed",
			artist_url: "https://x.com/meltt_ed",
			desc: "Based on IRL shenanigans with my dog and cat, haha. First image is with Pombon and Litten's default colors, while the second image is with colors that more closely resemble my pets.",
			date_str: "April 2026",
			tags: ["Pokemon", "Pombom", "Litten"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/eba67a1f9fd9.png"],
			thumbnail: "https://cdn.imgchest.com/files/0c3c873f5e22.png",
			title: "Vanan'Ice Request",
			artist: "CupofColors",
			artist_url: "https://bsky.app/profile/cupofcolors.bsky.social",
			desc: "Done as a request for CYL10. One of my favorite trios ever.",
			date_str: "April 2026",
			tags: ["Vocaloid", "KAITO", "Kagamine Len", "Kamui Gakupo", "Vanan'Ice", "Request"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/be0dd33535ee.png"],
			thumbnail: "https://cdn.imgchest.com/files/1ad0cd0b11b7.png",
			title: "Flavor Foley KaiLen",
			artist: "Fusenryo2",
			artist_url: "https://x.com/fusenryo2",
			desc: "A chance encounter between Electric Weekend Zone Kaito and Ego Renegade Boy Len.",
			date_str: "February 2026",
			tags: ["Vocaloid", "Kagamine Len", "KAITO", "KaiLen"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/6d7702a670bb.png"],
			thumbnail: "https://cdn.imgchest.com/files/e653b68b2e89.png",
			title: "Len's Biggest Fan",
			artist: "MissDash",
			artist_url: "https://bsky.app/profile/missdash.bsky.social",
			desc: "Done as a request for CYL10. MMJ Kaito would absolutely have this fan of MMJ Len, haha.",
			date_str: "February 2026",
			tags: ["Vocaloid", "KAITO", "Kagamine Len", "KaiLen"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/6e66faedbf16.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/2b56e849490f.png",
			title: "Sonamydow Heart Hands",
			artist: "Kiioki11",
			artist_url: "https://x.com/Kiioki11",
			desc: "A request I made for Sonic, Amy, and Shadow to make heart hands together.",
			date_str: "Janurary 2026",
			tags: ["Sonic the Hedgehog", "Sonic", "Amy Rose", "Shadow", "Sonamydow", "Request"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/36165dae0109.png"],
			thumbnail: "https://cdn.imgchest.com/files/b49b80ce57c4.png",
			title: "Ebi Jail",
			artist: "Waaaaven",
			artist_url: "https://x.com/waaaaven?s=20",
			desc: "A commission I got after 2 grueling days of non-stop tiering for Len's World Link. Waaaaven was also right there with me in the server, listening to Hitorinbo Envy on endless loop. In the end, it was all worth it as I finished at T25.",
			date_str: "September 2025",
			tags: ["Vocaloid", "Kagamine Len"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/dd608d55d10f.png"],
			thumbnail: "https://cdn.imgchest.com/files/deb650b7b8b5.png",
			title: "Monitoring Hajime",
			artist: "Yoshituber",
			artist_url: "https://x.com/yoshituber",
			desc: "Monitoring but make it KomaHina. This specific image references the part where Miku is standing outside of the person's door with a holographic bouquet and veil, which was re-interpreted as a ringbox for Nagito.",
			date_str: "April 2025",
			tags: ["Dangan Ronpa", "Komaeda Nagito", "KomaHina"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/dde99ac036c1.png"],
			thumbnail: "https://cdn.imgchest.com/files/2ed5d48ca6e8.png",
			title: "Dororenz Request",
			artist: "Legi",
			artist_url: "https://bsky.app/profile/homestar.bsky.social",
			desc: "Done as a CYL9 request. Lorenz and Dorothea absolutely love gossiping about others, haha.",
			date_str: "January 2025",
			tags: ["Fire Emblem 3H", "Lorenz", "Dorothea", "Dororenz", "Request"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/0a12b922f97e.png"],
			thumbnail: "https://cdn.imgchest.com/files/62235e8a9400.png",
			title: "Bring it on, Fake Heart!",
			artist: "Mango",
			artist_url: "https://x.com/mgosketches",
			desc: "A commission of Kagamine Len in his outfit from the song 'Fake Heart,' while doing the iconic fist heart pose from the song 'Bring it On.' I'm obssessed with his outfit from 'Fake Heart,' and I'm also jazzed that this has (as of 2026) still been the only non-Miku song commissioned for a Project Sekai anniversary. Hopefully we can get more Kagamine bangers.",
			date_str: "December 2024",
			tags: ["Vocaloid", "Kagamine Len"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/4d28cc110931.png"],
			thumbnail: "https://cdn.imgchest.com/files/5e560aa14eab.png",
			title: "Becoming the Protagonist",
			artist: "Moccha Kofii",
			artist_url: "https://x.com/moccha_kofii",
			desc: "A commission to celebrate the results of the 2024 Magical Mirai contest. Not only did a non-Miku song win for the first time, but it was a Len song no less! The piece draws parallels between the song 'Main Character,' which was performed in 2019, and the song 'Superhero,' which was the song that won the contest.",
			date_str: "August 2024",
			tags: ["Vocaloid", "Kagamine Len"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/a8f299864a58.png"],
			thumbnail: "https://cdn.imgchest.com/files/b8a85635190b.png",
			title: "Lavie Lavie Chu~",
			artist: "Huyandere",
			artist_url: "https://x.com/huyandere",
			desc: "A commission of Elm as Lavie from the Surii song, Lavie. The overlap betwen Elm and the character in the song was too strong to ignore.",
			date_str: "October 2023",
			tags: ["Fire Emblem Heroes", "Elm", "Vocaloid"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/7b1b0790e72f.png"],
			thumbnail: "https://cdn.imgchest.com/files/7089b23c9a23.png",
			title: "Chase and Wuya Redraw",
			artist: "Marcsedano",
			artist_url: "https://www.deviantart.com/marcsedano",
			desc: "A commission of my favorite villainous duo from Xiaolin Showdown. This is actually a redraw of a scene in S3 Ep12. I was flabbergasted when I realized that Chase had his hands around Wuya's waist lmao and had to draw attention to it.",
			date_str: "May 2022",
			tags: ["Xiaolin Showdown", "Chase Young", "Wuya", "Chuya"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/4cc6292a41fb.JPG"],
			thumbnail: "https://cdn.imgchest.com/files/7441337574e8.png",
			title: "Revolutionary Boy Lorenz",
			artist: "micstheMD",
			artist_url: "https://x.com/micstheMD?s=20",
			desc: "This was actually a 'gift' of sorts from my friend Miso as a prize for a little contest we held among our friends. Originally, I had a more ambitious idea of the 'dance' scene from the movie with pre-timeskip Dorothea and Lorenz dancing and their post-timeskip selves in the reflection of the water, but I scaled it back to fit the budget I had.",
			date_str: "September 2021",
			tags: ["Fire Emblem 3H", "Dorothea", "Lorenz", "Dororenz"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/4c24d50ab133.png"],
			thumbnail: "https://cdn.imgchest.com/files/23c61867cf2b.png",
			title: "Flyway KaiLen",
			artist: "Legi",
			artist_url: "https://bsky.app/profile/homestar.bsky.social",
			desc: "A birthday gift from my boyfriend of Kaito and Len in their Flyway outfits from the Magical Mirai concert. As a bit of a troll, this pose is specifically referencing a shot from the fan animation for Twiddlefinger, a song that we had a bit of brainrot over.",
			date_str: "September 2025",
			tags: ["Vocaloid", "Kagamine Len", "KAITO", "KaiLen", "Gift"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/72273af54c3e.png"],
			thumbnail: "https://cdn.imgchest.com/files/a0aaddb67cbb.png",
			title: "Summer Chrobin Gift, the Sequel",
			artist: "Mason",
			artist_url: "https://bsky.app/profile/misokatsuhaumai.bsky.social",
			desc: "A gift from my friend, José! Chrom and Robin are enjoying a fun beach date.",
			date_str: "March 2026",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin", "Gift"],
			hidden: false
		},						
		{
			src: ["https://cdn.imgchest.com/files/5abf6cad3b05.png"],
			thumbnail: "https://cdn.imgchest.com/files/0f2916b8bb47.png",
			title: "Chrobin Gift",
			artist: "merylemons",
			artist_url: "https://x.com/merylemons",
			desc: "A birthday gift from my friend, Eeby! I've always adored merylemons' style so it was quite the wonderful surprise to get a piece from them.",
			date_str: "September 2025",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin", "Gift"],
			hidden: false
		},					
		{
			src: ["https://cdn.imgchest.com/files/eff39437a538.png"],
			thumbnail: "https://cdn.imgchest.com/files/b012af8ce0f2.png",
			title: "Summer Robin Gift",
			artist: "José Julio",
			artist_url: "https://bsky.app/profile/josejuliojmz.bsky.social",
			desc: "A birthday gift from my friend, José! I love how happy she looks.",
			date_str: "September 2025",
			tags: ["Fire Emblem", "Female Robin", "Gift"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/4b30fd289ee4.png"],
			thumbnail: "https://cdn.imgchest.com/files/62ba0f681b09.png",
			title: "A Day in the Life of the Exalt Family",
			artist: "Loustica",
			artist_url: "https://bsky.app/profile/loustica-lucia.bsky.social",
			desc: "A birthday gift from my friend, Silent! Was a pleasant surprise to get a piece from my fellow Chrobin fan, Loustica.",
			date_str: "September 2024",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Lucina", "Male Morgan", "Exalt Family", "Gift"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/81da4e58e69b.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/0f422b69496b.png",
			title: "Stage Sekai Lucina and Morgan",
			artist: "Katarina_Neko",
			artist_url: "https://x.com/katarina_neko",
			desc: "A birthday gift from my friend, ZX, of Lucina and Morgan dressed as the Stage Sekailoids!",
			date_str: "September 2024",
			tags: ["Fire Emblem", "Lucina", "Male Morgan", "Exalt Family", "Vocaloid", "Gift"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/c5b5268b89cc.png"],
			thumbnail: "https://cdn.imgchest.com/files/69349c5dce36.png",
			title: "Birthday Comic",
			artist: "Siren",
			artist_url: "https://x.com/ladylawga",
			desc: "A birthday gift from my friend, Silent. A fun comic that references some of my personal interests, like ballroom dancing or DDR.",
			date_str: "September 2023",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Lucina", "Male Morgan", "Exalt Family", "Gift", "Comic"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/1f585d2561df.png"],
			thumbnail: "https://cdn.imgchest.com/files/11c1dcf91dbf.png",
			title: "Family Feud",
			artist: "Ivan Shinoda",
			artist_url: "https://x.com/ivanshinoda10",
			desc: "A collab with Mifi. The idea to do a Family Feud parody was his, and most of the script was done by me. You can also see a lot of the prototype designs that I would later refine for my modern AU designs.",
			date_str: "March 2023",
			tags: ["Fire Emblem Collab", "Persona", "Chrom", "Female Robin", "Male Morgan", "Lucina", "Joker", "Exalt Family", "Collab", "Comic"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/9e89f08b8c8b.png"],
			thumbnail: "https://cdn.imgchest.com/files/67eafa99506d.png",
			title: "Baking Cookies",
			artist: "TruJek",
			artist_url: "https://x.com/true_jek_art",
			desc: "A gift from Yoostink in exchange for the Hooters collab. A very cute piece of Robin baking some delicious sugar cookies for her fellow Smash roster friends.",
			date_str: "January 2023",
			tags: ["Fire Emblem", "Smash Bros", "Female Robin", "Gift"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/7d710918f7b7.png"],
			thumbnail: "https://cdn.imgchest.com/files/34e5f5270a83.png",
			title: "Beware the Tactician",
			artist: "AdamCreyton",
			artist_url: "https://x.com/AdamCreyton",
			desc: "A birthday gift from my friend, Miso. He was the one who got me into the swamp of villainess comics, the first of which was... okay it was actually 'The Old Man is Reincarnated as a Villainess' but the second one was 'Beware the Villainess!' So this was a fun callback.",
			date_str: "September 2022",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin", "Beware the Villainess", "Gift"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/56d5c7dfaccd.png"],
			thumbnail: "https://cdn.imgchest.com/files/4aaeb05af7eb.png",
			title: "Family Outing",			
			artist: "Siren",
			artist_url: "https://x.com/ladylawga",
			desc: "A birthday gift from my friend, Silent. While Chrom and Robin are enjoying their moment of peace, Morgan is causing a bit of chaos for his sister in the background.",
			date_str: "September 2022",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Lucina", "Male Morgan", "Exalt Family", "Gift"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/e1953b82ba30.png"],
			thumbnail: "https://cdn.imgchest.com/files/78136ff6bd54.png",
			title: "Summer Beach Party",
			artist: "RedKite",
			artist_url: "https://x.com/RedKite333?s=20",
			desc: "A large collab with several other people for a fun beach piece.",
			date_str: "June 2022",
			tags: ["Fire Emblem Collab", "Chrom", "Female Robin", "Collab"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/756cf2654782.png"],
			thumbnail: "https://cdn.imgchest.com/files/e7f0111063a1.png",
			title: "Sleepover Gossip",
			artist: "Ly_art01",
			artist_url: "https://x.com/Ly_art01",
			desc: "A collab with DarthMarth. Robin and Lissa are having a fun sleepover, and gossipping a bit about their crushes. The sleepwear design for Robin was based on her armor break from Warriors.",
			date_str: "March 2022",
			tags: ["Fire Emblem Collab", "Female Robin", "Lissa", "Collab"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/56105ab2cc8b.png"],
			thumbnail: "https://cdn.imgchest.com/files/56105ab2cc8b.png",
			title: "Robin Skill Issue",
			artist: "Rita",
			artist_url: "https://x.com/_anachaga",
			desc: "A gift from my friend, ZX!",
			date_str: "March 2022",
			tags: ["Fire Emblem", "Female Robin", "Gift"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/0a634ec73781.png"],
			thumbnail: "https://cdn.imgchest.com/files/59c8a5292729.png",
			title: "Hooters Robin and Lucina",
			artist: "Shugo",
			artist_url: "https://x.com/hiomaika",
			desc: "A collab with Yoostink and others. Lucina and Robin are hard at work earning tips so that they can +10 Brave Chrom.",
			date_str: "February 2022",
			tags: ["Fire Emblem Collab", "Female Robin", "Lucina", "Lissa", "Ophelia", "Leonie", "Noire", "Collab"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/cfff7c580b47.png"],
			thumbnail: "https://cdn.imgchest.com/files/cfff7c580b47.png",
			title: "Robin Headpat",
			artist: "DeliiChan5",
			artist_url: null,
			desc: "A gift from DarthMarth of Robin receiving a headpat from Chrom.",
			date_str: "December 2021",
			tags: ["Fire Emblem", "Female Robin", "Chrobin", "Gift"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/6088636291a1.png"],
			thumbnail: "https://cdn.imgchest.com/files/abfcbfaa26a7.png",
			title: "Hoenn Trainers Chrom and Robin",
			artist: "Nozukat",
			artist_url: "https://x.com/nozukat",
			desc: "A gift from my boyfriend of Chrom and Robin in modified versions of the Hoenn trainers' outfits. Poses are based on the Ace Trainers.",
			date_str: "September 2021",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin", "Gift"],
			hidden: false
		},	
		{
			src: ["https://cdn.imgchest.com/files/dfe4852aca20.png"],
			thumbnail: "https://cdn.imgchest.com/files/8a58f5453c6c.png",
			title: "Sinnoh Trainers Robin and Sumia",
			artist: "Nozukat",
			artist_url: "https://x.com/nozukat",
			desc: "A gift from my boyfriend of Robin and Sumia in modified versions of the Sinnoh trainers' outfits. Poses are based on the Honeymooners.",
			date_str: "September 2021",
			tags: ["Fire Emblem", "Male Robin", "Sumia", "Robmia", "Gift"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/3e7b1d2017c8.png"],
			thumbnail: "https://cdn.imgchest.com/files/6eb9e9ee6aed.png",
			title: "Dorothea and Lorenz",
			artist: "Siren",
			artist_url: "https://x.com/ladylawga",
			desc: "A birthday gift from my friend, Silent. As a funny backstory, I used to refer to this ship as Lorenzthea, which was misinterpreted as Lorenz and Lysithea. So when I received a fully colored illustration of Lorenz and Lysithea, I was very confused. Thankfully, Siren was gracious enough to do a quick re-do. From there onwards, I call the ship Dororenz instead haha.",
			date_str: "September 2021",
			tags: ["Fire Emblem 3H", "Dorothea", "Lorenz", "Dororenz", "Gift"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/7e143c96d8a0.png"],
			thumbnail: "https://cdn.imgchest.com/files/02c298f91b18.png",
			title: "Chrom with a Burger",
			artist: "SugarBunGaius",
			artist_url: "https://x.com/sugarbungaius",
			desc: "A gift from my friend, Miso, of Chrom with my boyfriend's favorite food, a burger.",
			date_str: "July 2021",
			tags: ["Fire Emblem", "Chrom", "Gift"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/05f2cf416e38.png"],
			thumbnail: "https://cdn.imgchest.com/files/b6cc97f90e08.png",
			title: "Robin with Boba Tea",
			artist: "SugarBunGaius",
			artist_url: "https://x.com/sugarbungaius",
			desc: "A gift from my friend, Miso, of Robin with my favorite food, boba tea.",
			date_str: "July 2021",
			tags: ["Fire Emblem", "Female Robin", "Gift"],
			hidden: false
		},						
		{
			src: ["https://cdn.imgchest.com/files/6e57cf4cfd2b.png"],
			thumbnail: "https://cdn.imgchest.com/files/838c55c9d4c3.png",
			title: "Summer Chrobin Gift",
			artist: "Siren",
			artist_url: "https://x.com/ladylawga",
			desc: "A birthday gift from my friend, Silent. A cute scene of Chrom and Robin enjoying their beach date.",
			date_str: "September 2020",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin", "Gift"],
			hidden: false
		}
	]
};
