var data = {
	images: [
		{
			src: [""],
			thumbnail: "",
			title: "Placeholder Entry",
			artist: "Placeholder Entry",
			artist_url: null,
			desc: "Do not delete this. You can use this to set the order the tags show up in the dropdown.",
			date_str: "Beginning of Time",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Lucina", "Male Morgan", "Inigo", "Severa", "Male Robin", "Sumia", "Cynthia", "Female Morgan", "Owain", "Gerome", "Virion", "Olivia", "Gaius", "Cordelia", "Vaike", "Lissa", "Frederick", "Cherche", "Soleil", "Caeldori", "Ophelia", "Damien", "Chrobin", "Exalt Family", "Lucinigo", "Sevimorgan", "Robmia", "Violet Family", "Owainthia", "Geromorgan", "Viriolivia", "Gaiusdelia", "Vaikessa", "Chercherick", "Roleswap AU", "Modern AU", "Vocaloid", "Kagamine Len"],
			hidden: true
		},	
		{
			src: [""],
			thumbnail: "",
			title: "",
			artist: "",
			artist_url: "",
			desc: "",
			date_str: "",
			tags: [""],
			hidden: true
		},
		{
			src: ["https://cdn.imgchest.com/files/e38f05d46308.png"],
			thumbnail: "https://cdn.imgchest.com/files/87c7456b23c2.png",
			title: "Violet Family Picnic",
			artist: "ArayaEjiri",
			artist_url: "https://x.com/ArayaEjiri",
			desc: "A scene of the Violet family enjoying a family picnic.",
			date_str: "May 2025",
			tags: ["Fire Emblem", "Male Morgan", "Sumia", "Cynthia", "Female Morgan", "Owain", "Gerome", "Ophelia", "Damien", "Violet Family", "Owanthia", "Geromorgan"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/b6aec78d7548.png"],
			thumbnail: "https://cdn.imgchest.com/files/a18d463d1ece.png",
			title: "Exalt Family Christmas",
			artist: "ArayaEjiri",
			artist_url: "https://x.com/ArayaEjiri",
			desc: "A scene of the Exalt family enjoying their Christmas eve.",
			date_str: "December 2024",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Lucina", "Inigo", "Male Morgan", "Severa", "Caeldori", "Soleil", "Exalt Family", "Lucinigo", "Sevimorgan"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/ef6fa370bb85.png"],
			thumbnail: "https://cdn.imgchest.com/files/78734ff6a632.png",
			title: "Super Mario Chrobin",
			artist: "Moccha Kofii",
			artist_url: "https://x.com/moccha_kofii",
			desc: "Chrom and Robin as iconic video game couples. Because Robin's red palette gave her blonde hair, and Peach also had a red palette that gave her a red dress, those colors were used. And since we're in the realm of Smash Ultimate, Chrom Mii (whose body type more closely replicates Mario's) is here to steal Chrom's girl.",
			date_str: "February 2024",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin", "Super Mario Brothers"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/5706d10e5145.png"],
			thumbnail: "https://cdn.imgchest.com/files/f32db6474a45.png",
			title: "Legend of Chrobin",
			artist: "Moccha Kofii",
			artist_url: "https://x.com/moccha_kofii",
			desc: "Chrom and Robin as iconic video game couples. The parallels between Zelda who became a dragon in Tears of the Kingdom and Robin who becomes Grima in a bad timeline was not lost on me. It was also very easy to incorporate Chrom's brand into the design of his right arm.",
			date_str: "February 2024",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin", "Legend of Zelda"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/1a3d128f2b85.png"],
			thumbnail: "https://cdn.imgchest.com/files/fa2f9101eb79.png",
			title: "Chrobin the Hedgehogs",
			artist: "Moccha Kofii",
			artist_url: "https://x.com/moccha_kofii",
			desc: "Chrom and Robin as iconic video game couples. I was initially considering using the Sonic Boom outfits, but the Murder of Sonic was such a great game that I had to go with that one instead. I love how Moccha drew the background, giving it an incredibly stylistic slant that is just so fitting for something from the Sonic series.",
			date_str: "February 2024",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin", "Sonic the Hedgehog"],
			hidden: false
		},						
		{
			src: ["https://cdn.imgchest.com/files/df8f198bc12e.png"],
			thumbnail: "https://cdn.imgchest.com/files/5f5c2afc566c.png",
			title: "Chrom - Prince",
			artist: "camiCR",
			artist_url: "https://x.com/camilitroxCR",
			desc: "An emote of Chrom extending his hand in a princely manner. Pairs with the female Robin one",
			date_str: "January 2022",
			tags: ["Fire Emblem", "Chrom"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/321547aca5e8.png"],
			thumbnail: "https://cdn.imgchest.com/files/321547aca5e8.png",
			title: "F!Robin - Wow",
			artist: "camiCR",
			artist_url: "https://x.com/camilitroxCR",
			desc: "An emote of Robin swooning over something. Pairs with the Chrom one.",
			date_str: "January 2022",
			tags: ["Fire Emblem", "Female Robin"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/8c8451a7773a.png"],
			thumbnail: "https://cdn.imgchest.com/files/8c8451a7773a.png",
			title: "Lucina - Disapproval",
			artist: "camiCR",
			artist_url: "https://x.com/camilitroxCR",
			desc: "An emote of Lucina giving a thumbs down. Pairs with the male Morgan one. (I only just now noticed that Lucina is missing her brand as well, lol, so I manually added it myself.)",
			date_str: "January 2022",
			tags: ["Fire Emblem", "Lucina"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/cfbb29529a8d.png"],
			thumbnail: "https://cdn.imgchest.com/files/cfbb29529a8d.png",
			title: "M!Morgan - Approval",
			artist: "camiCR",
			artist_url: "https://x.com/camilitroxCR",
			desc: "An emote of Morgan giving a thumbs up. Pairs with the Lucina one.",
			date_str: "January 2022",
			tags: ["Fire Emblem", "Male Morgan"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/90a79dc6426b.png","https://cdn.imgchest.com/files/bd01b9c576ba.png"],
			thumbnail: "https://cdn.imgchest.com/files/90a79dc6426b.png",
			title: "Cynthia - Excited",
			artist: "camiCR",
			artist_url: "https://x.com/camilitroxCR",
			desc: "An emote of Cynthia being excited. This is a reference to a Luffy expression, as requested by my boyfriend. One version is my headcanon of her as having brown hair and the other version is his headcanon of her having purple hair.",
			date_str: "January 2022",
			tags: ["Fire Emblem", "Cynthia"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/b9e20f600f5c.png"],
			thumbnail: "https://cdn.imgchest.com/files/b9e20f600f5c.png",
			title: "F!Morgan - Sour",
			artist: "camiCR",
			artist_url: "https://x.com/camilitroxCR",
			desc: "An emote of Morgan making a sour face. This is a reference to a Luffy expression, as requested by my boyfriend.",
			date_str: "January 2022",
			tags: ["Fire Emblem", "Female Morgan"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/2bbfa35767a0.png"],
			thumbnail: "https://cdn.imgchest.com/files/5cfb733ce3c3.png",
			title: "Lucina and Morgan as the Brief siblings",
			artist: "Nosoiquio",
			artist_url: "https://x.com/nosoiquio",
			desc: "Given the obvious parallels between Lucina and Trunks, it only felt fitting to pay homage to two of my favorite characters. And naturally, Morgan had to join his sister. It was an interesting challenge to design a male version of Bulla's outfit that would still be recognizable as hers, considering someone else would be wearing it, but I think I did a good job.",
			date_str: "September 2021",
			tags: ["Fire Emblem", "Lucina", "Male Morgan", "Exalt Family", "Dragonball Z"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/5eb772bfcbda.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/e19e90a58ec7.png",
			title: "The King of Plegia and Queen of Ylisse",
			artist: "Picnicic",
			artist_url: "https://x.com/picnicic",
			desc: "A skeb-style commission in which Chrom was born Plegian and Robin was born Ylissean. It was fun to reimagine where their brands would be in this scenario. The background also never ceases to take my breath away.",
			date_str: "August 2021",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/0720edc532b5.png"],
			thumbnail: "https://cdn.imgchest.com/files/8d2c09898d43.png",
			title: "Imitation Black Chrobin",
			artist: "HaruAki",
			artist_url: "https://x.com/scl_HaruAki",
			desc: "As a major Vanan'Ice fan, it was a dream come true to get to see Chrom and Robin drawn by the HaruAki, especially since I was unsure if she would take non-OC requests. Naturally, I had to request them dressed as Kaito and Len from 'IMITATION Black,' as who else would know these outfits better than HaruAki herself? Definitely one of my absolute favorite commissions ever.",
			date_str: "July 2021",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin", "Vocaloid"],
			hidden: true
		},		
		{
			src: ["https://cdn.imgchest.com/files/627af6568ee9.png"],
			thumbnail: "https://cdn.imgchest.com/files/c539a4b0718e.png",
			title: "Mother's Pendant",
			artist: "Yunah",
			artist_url: "https://x.com/LordYunaa",
			desc: "When I saw that Summer Robin had a necklace, my mind immediately went to the pendant that Lucina mentioned receiving from her mother in her Gerome supports. And of course, I had to headcanon around this.",
			date_str: "July 2021",
			tags: ["Fire Emblem", "Female Robin", "Lucina", "Exalt Family"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/deebbdd822e8.png"],
			thumbnail: "https://cdn.imgchest.com/files/53a0d502e854.png",
			title: "Chrom and Morgan have achieved B-ranked support",
			artist: "natsuB_Bkoge",
			artist_url: "https://x.com/natsuB_Bkoge",
			desc: "An angsty piece exploring the relationship between fallen Morgan and Risen King Chrom. They're both shells of their former selves and yet... perhaps they've found some comfort in the invisible ties that still tie them together.",
			date_str: "June 2021",
			tags: ["Fire Emblem", "Chrom", "Male Morgan", "Exalt Family"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/3f62056e63b3.png"],
			thumbnail: "https://cdn.imgchest.com/files/bbf05808f341.png",
			title: "Box Art",
			artist: "SnipperPool",
			artist_url: "https://x.com/SnipperPool",
			desc: "A commission done by a friend, where Morgan and Owain have taken the place of their fathers on the box art. Morgan is in the Grandmaster class while Owain is in the Dread Fighter class. Background edits were done by me.",
			date_str: "May 2021",
			tags: ["Fire Emblem", "Male Morgan", "Owain"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/1bb3093d16ef.png"],
			thumbnail: "https://cdn.imgchest.com/files/c52f7f947077.png",
			title: "The Three Mask-eteers",
			artist: "Riidi",
			artist_url: "https://x.com/m_riidi",
			desc: "A commission of Inigo, Gerome, and Lucina dressed as Roy, Marcus, and Lilina respectively. A little more customization went into Lucina's outfit to reference Robin as her mother.",
			date_str: "April 2021",
			tags: ["Fire Emblem", "Inigo", "Gerome", "Lucina"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/91df7ce44b5d.png"],
			thumbnail: "https://cdn.imgchest.com/files/9693ae8fec50.png",
			title: "The New Pegasus Trio",
			artist: "Riidi",
			artist_url: "https://x.com/m_riidi",
			desc: "A commission of Cynthia, Severa, and Morgan dressed as Palla, Catria, and Est respectively.",
			date_str: "April 2021",
			tags: ["Fire Emblem", "Cynthia", "Severa", "Female Morgan"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/38401c923291.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/be1c2540adfd.png",
			title: "Ballroom Chrom and Robin",
			artist: "Erumei24",
			artist_url: "https://x.com/erumei24",
			desc: "A commission of Chrom and Robin wearing a slightly tweaked version of ballroom Sigurd and Deirdre's outfits. I've always enjoyed the parallels between these two couples, and given how much I also love ballroom dancing, this felt like a no-brainer for me to commission. For a long while, this Robin was also my profile picture on Twitter because of how much I truly adore this piece.",
			date_str: "March 2021",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/2a55bed817ed.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/d96f0c8f30b1.png",
			title: "Wedding Robin and Sumia",
			artist: "Erumei24",
			artist_url: "https://x.com/erumei24",
			desc: "A commission of Robin and Sumia wearing a slightly tweaked version of wedding Marth and Caeda's outfits.  This was a gift for my boyfriend for our anniversary. Sumia as Caeda is obvious, but Robin as Marth is a nod to his support with Tiki in which she outright compares the two and says that Robin is more like Marth than Chrom is. This is also one of my personal favorite pieces that I have ever commissioned.",
			date_str: "March 2021",
			tags: ["Fire Emblem", "Male Robin", "Sumia", "Robmia"],
			hidden: false
		},
			{
			src: ["https://cdn.imgchest.com/files/d86446cb9c0a.png"],
			thumbnail: "https://cdn.imgchest.com/files/01c79a434cd9.png",
			title: "Learning from Dad - Inigo Side",
			artist: "EdithSotoArt",
			artist_url: "https://x.com/EdithSotoArt",
			desc: "Since Lucina inherited her genius from her mother, Inigo thought to impress her by showing off his own tactical prowess. However, chess is a little harder than he expected… Thankfully, his father is a patient teacher, especially when he has his cup of tea to sip on while waiting for Inigo to make his next move.",
			date_str: "March 2021",
			tags: ["Fire Emblem", "Virion", "Inigo", "Lucina", "Viriolivia", "Lucinigo"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/f1b9e6767d6b.png"],
			thumbnail: "https://cdn.imgchest.com/files/d12741cc6e9f.png",
			title: "Learning from Dad - Severa Side",
			artist: "EdithSotoArt",
			artist_url: "https://x.com/EdithSotoArt",
			desc: "While Severa would sooner die than touch a bug, bug-themed cookies were an acceptable enough substitute. After all, the way to a person’s heart is through their stomach… or so her daddy says. And with his help, there was no way she could fail to win Morgan’s favor!",
			date_str: "March 2021",
			tags: ["Fire Emblem", "Gaius", "Cordelia", "Male Morgan", "Gaiusdelia", "Sevimorgan"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/f1ea7100c60f.png"],
			thumbnail: "https://cdn.imgchest.com/files/f1ea7100c60f.png",
			title: "Chrom - Confusion",
			artist: "Rita",
			artist_url: "https://x.com/_anachaga",
			desc: "An emote of Chrom being confused (referred to as Chromfusion). Pairs with the female Robin one.",
			date_str: "February 2021",
			tags: ["Fire Emblem", "Chrom"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/dca93862517f.png"],
			thumbnail: "https://cdn.imgchest.com/files/dca93862517f.png",
			title: "F!Robin - I See!",
			artist: "Rita",
			artist_url: "https://x.com/_anachaga",
			desc: "A emote of Robin doing the 'naruhodo!' pose. Pairs with the Chrom one.",
			date_str: "February 2021",
			tags: ["Fire Emblem", "Female Robin"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/6206c261de4d.png"],
			thumbnail: "https://cdn.imgchest.com/files/6206c261de4d.png",
			title: "Lucina - Cool Cry",
			artist: "Rita",
			artist_url: "https://x.com/_anachaga",
			desc: "An emote of Lucina with sunglasses crying while doing double fingerguns.",
			date_str: "February 2021",
			tags: ["Fire Emblem", "Lucina"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/2e5268fd9de4.png"],
			thumbnail: "https://cdn.imgchest.com/files/2e5268fd9de4.png",
			title: "M!Morgan - Smug",
			artist: "Rita",
			artist_url: "https://x.com/_anachaga",
			desc: "An emote of Morgan being smug.",
			date_str: "February 2021",
			tags: ["Fire Emblem", "Male Morgan"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/2114c03b4b16.png"],
			thumbnail: "https://cdn.imgchest.com/files/2114c03b4b16.png",
			title: "Sumia - Bashful",
			artist: "Rita",
			artist_url: "https://x.com/_anachaga",
			desc: "An emote of Sumia being bashful, as requested by my boyfriend. Pairs with the male Robin one.",
			date_str: "February 2021",
			tags: ["Fire Emblem", "Sumia"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/7f59881310e6.png"],
			thumbnail: "https://cdn.imgchest.com/files/7f59881310e6.png",
			title: "M!Robin - Sheepish",
			artist: "Rita",
			artist_url: "https://x.com/_anachaga",
			desc: "An emote of Robin laughing while embarrassed, as requested by my boyfriend. Pairs with the Sumia one.",
			date_str: "February 2021",
			tags: ["Fire Emblem", "Male Robin"],
			hidden: false
		},					
		{
			src: ["https://cdn.imgchest.com/files/5fd89d608dbc.jpeg"],
			thumbnail: "https://cdn.imgchest.com/files/e0d5192a814b.png",
			title: "New Years Chrom and Morgan",
			artist: "Vallurite",
			artist_url: "https://x.com/Vallurite?s=20",
			desc: "Chrom and Morgan are ringing in the New Year with their wonderful new kimonos. And they're not alone, as Chrom has Robin on his hagiota and Morgan has Lucina on his karuta card. Chrom and Lucina's kimonos are based on their design from the Daily Life of Heroes manga, while Morgan and Robin's are my own design. And of course, I couldn't resist giving Morgan the kagami mochi accessory for the cheeky connection to oranges.",
			date_str: "January 2021",
			tags: ["Fire Emblem", "Male Morgan", "Chrom", "Exalt Family"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/37e6483f71a0.png"],
			thumbnail: "https://cdn.imgchest.com/files/4136e13d6fda.png",
			title: "Winter Lucina and Morgan",
			artist: "Majibomber",
			artist_url: "https://x.com/majibomber",
			desc: "Celebrating Christmas with a commission of Lucina and Morgan dressed as their ancestors, Marth and Elice. Background (which is a FEH asset) was added by me! As an aside, this is a period of time where I wasn't consistent with Morgan's eye color hence the blue eyes despite my personal preference for brown eyes on him.",
			date_str: "December 2020",
			tags: ["Fire Emblem", "Lucina", "Male Morgan", "Exalt Family"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/4fae0933463d.png"],
			thumbnail: "https://cdn.imgchest.com/files/28e76c5c8006.png",
			title: "Taking After Their Parents",
			artist: "Nootnootles",
			artist_url: "https://x.com/nootnootles",
			desc: "A commission I got from a friend of mine of the Morgans taking after their parents. Male Morgan is holding Falchion while female Morgan is holding Luna. Some of the details on female Morgan are also based on my boyfriend's preferences, such as having glasses or holding a Piranha 'flower.'",
			date_str: "October 2020",
			tags: ["Fire Emblem", "Male Morgan", "Female Morgan"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/183f4a393132.png"],
			thumbnail: "https://cdn.imgchest.com/files/c91c92b1dc63.png",
			title: "Great Lord Lucina and Bow Knight Inigo",
			artist: "Lace",
			artist_url: "https://bsky.app/profile/adelleein.bsky.social",
			desc: "One of the very first commissions I ever got, which was done for a donation rally. The commission depicts my preferred final classes for Lucina and Inigo, which is Great Lord and Bow Knight respectively. The flower petals around Lucina are a reference to the skill Ignis. The bow sprite is Dignified Bow, and the sword sprite is Skuld.",
			date_str: "August 2020",
			tags: ["Fire Emblem", "Lucina", "Inigo", "Lucinigo"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/08fa2ad5fa25.png"],
			thumbnail: "https://cdn.imgchest.com/files/cff158f2e7c2.png",
			title: "Grandmaster Morgan and Dark Flier Severa",
			artist: "Lace",
			artist_url: "https://bsky.app/profile/adelleein.bsky.social",
			desc: "One of the very first commissions I ever got, which was done for a donation rally. The commission depicts my preferred final classes for Morgan and Severa, which is Grandmaster and Dark Flier respectively. The green tome sprite is Excalibur.",
			date_str: "August 2020",
			tags: ["Fire Emblem", "Severa", "Male Morgan", "Sevimorgan"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/80989f8549d0.png"],
			thumbnail: "https://cdn.imgchest.com/files/aa2871bf95df.png",
			title: "The Prince of Darkness",
			artist: "Lucas/Sun",
			artist_url: "https://x.com/ultimatesun_",
			desc: "A commission done by my friend of Len as Ralsei. As for the rest of the Fun Gang, I would pick Miku as Kris and Rin as Susie.",
			date_str: "May 2026",
			tags: ["Vocaloid", "Kagamine Len", "Deltarune"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/813cdea78d64.png", "https://cdn.imgchest.com/files/4ff392ac8b00.png"],
			thumbnail: "https://cdn.imgchest.com/files/4f2c1cb25400.png",
			title: "Pombon and Litten",
			artist: "Melt/Ed",
			artist_url: "https://x.com/meltt_ed",
			desc: "Based on IRL shenanigans with my dog and cat, haha. First image is with Pombon and Litten's default colors, while the second image is with colors that more closely resemble my pets.",
			date_str: "April 2026",
			tags: ["Pokemon", "Pombom", "Litten"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/eba67a1f9fd9.png"],
			thumbnail: "https://cdn.imgchest.com/files/0c3c873f5e22.png",
			title: "Vanan'Ice Request",
			artist: "CupofColors",
			artist_url: "https://bsky.app/profile/cupofcolors.bsky.social",
			desc: "Done as a request for CYL10. One of my favorite trios ever.",
			date_str: "April 2026",
			tags: ["Vocaloid", "KAITO", "Kagamine Len", "Kamui Gakupo", "Vanan'Ice", "Request"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/be0dd33535ee.png"],
			thumbnail: "https://cdn.imgchest.com/files/1ad0cd0b11b7.png",
			title: "Flavor Foley KaiLen",
			artist: "Fusenryo2",
			artist_url: "https://x.com/fusenryo2",
			desc: "A chance encounter between Electric Weekend Zone Kaito and Ego Renegade Boy Len.",
			date_str: "February 2026",
			tags: ["Vocaloid", "Kagamine Len", "KAITO", "KaiLen"],
			hidden: false
		},			
		{
			src: ["https://cdn.imgchest.com/files/6d7702a670bb.png"],
			thumbnail: "https://cdn.imgchest.com/files/e653b68b2e89.png",
			title: "Len's Biggest Fan",
			artist: "MissDash",
			artist_url: "https://bsky.app/profile/missdash.bsky.social",
			desc: "Done as a request for CYL10. MMJ Kaito would absolutely have this fan of MMJ Len, haha.",
			date_str: "February 2026",
			tags: ["Vocaloid", "KAITO", "Kagamine Len", "KaiLen"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/6e66faedbf16.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/2b56e849490f.png",
			title: "Sonamydow Heart Hands",
			artist: "Kiioki11",
			artist_url: "https://x.com/Kiioki11",
			desc: "A request I made for Sonic, Amy, and Shadow to make heart hands together.",
			date_str: "Janurary 2026",
			tags: ["Sonic the Hedgehog", "Sonic", "Amy Rose", "Shadow", "Sonamydow", "Request"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/36165dae0109.png"],
			thumbnail: "https://cdn.imgchest.com/files/b49b80ce57c4.png",
			title: "Ebi Jail",
			artist: "Waaaaven",
			artist_url: "https://x.com/waaaaven?s=20",
			desc: "A commission I got after 2 grueling days of non-stop tiering for Len's World Link. Waaaaven was also right there with me in the server, listening to Hitorinbo Envy on endless loop. In the end, it was all worth it as I finished at T25.",
			date_str: "September 2025",
			tags: ["Vocaloid", "Kagamine Len"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/dd608d55d10f.png"],
			thumbnail: "https://cdn.imgchest.com/files/deb650b7b8b5.png",
			title: "Monitoring Hajime",
			artist: "Yoshituber",
			artist_url: "https://x.com/yoshituber",
			desc: "Monitoring but make it KomaHina. This specific image references the part where Miku is standing outside of the person's door with a holographic bouquet and veil, which was re-interpreted as a ringbox for Nagito.",
			date_str: "April 2025",
			tags: ["Dangan Ronpa", "Komaeda Nagito", "KomaHina"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/0a12b922f97e.png"],
			thumbnail: "https://cdn.imgchest.com/files/62235e8a9400.png",
			title: "Bring it on, Fake Heart!",
			artist: "Mango",
			artist_url: "https://x.com/mgosketches",
			desc: "A commission of Kagamine Len in his outfit from the song 'Fake Heart,' while doing the iconic fist heart pose from the song 'Bring it On.' I'm obssessed with his outfit from 'Fake Heart,' and I'm also jazzed that this has (as of 2026) still been the only non-Miku song commissioned for a Project Sekai anniversary. Hopefully we can get more Kagamine bangers.",
			date_str: "December 2024",
			tags: ["Vocaloid", "Kagamine Len"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/4d28cc110931.png"],
			thumbnail: "https://cdn.imgchest.com/files/5e560aa14eab.png",
			title: "Becoming the Protagonist",
			artist: "Moccha Kofii",
			artist_url: "https://x.com/moccha_kofii",
			desc: "A commission to celebrate the results of the 2024 Magical Mirai contest. Not only did a non-Miku song win for the first time, but it was a Len song no less! The piece draws parallels between the song 'Main Character,' which was performed in 2019, and the song 'Superhero,' which was the song that won the contest.",
			date_str: "August 2024",
			tags: ["Vocaloid", "Kagamine Len"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/a8f299864a58.png"],
			thumbnail: "https://cdn.imgchest.com/files/b8a85635190b.png",
			title: "Lavie Lavie Chu~",
			artist: "Huyandere",
			artist_url: "https://x.com/huyandere",
			desc: "A commission of Elm as Lavie from the Surii song, Lavie. The overlap betwen Elm and the character in the song was too strong to ignore.",
			date_str: "October 2023",
			tags: ["Fire Emblem Heroes", "Elm", "Vocaloid"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/7b1b0790e72f.png"],
			thumbnail: "https://cdn.imgchest.com/files/7089b23c9a23.png",
			title: "Chase and Wuya Redraw",
			artist: "Marcsedano",
			artist_url: "https://www.deviantart.com/marcsedano",
			desc: "A commission of my favorite villainous duo from Xiaolin Showdown. This is actually a redraw of a scene in S3 Ep12. I was flabbergasted when I realized that Chase had his hands around Wuya's waist lmao and had to draw attention to it.",
			date_str: "May 2022",
			tags: ["Xiaolin Showdown", "Chase Young", "Wuya", "Chuya"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/4cc6292a41fb.JPG"],
			thumbnail: "https://cdn.imgchest.com/files/7441337574e8.png",
			title: "Revolutionary Boy Lorenz",
			artist: "micstheMD",
			artist_url: "https://x.com/micstheMD?s=20",
			desc: "This was actually a 'gift' of sorts from my friend Miso as a prize for a little contest we held among our friends. Originally, I had a more ambitious idea of the 'dance' scene from the movie with pre-timeskip Dorothea and Lorenz dancing and their post-timeskip selves in the reflection of the water, but I scaled it back to fit the budget I had.",
			date_str: "September 2021",
			tags: ["Fire Emblem 3H", "Dorothea", "Lorenz", "Dororenz"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/4c24d50ab133.png"],
			thumbnail: "https://cdn.imgchest.com/files/23c61867cf2b.png",
			title: "Flyway KaiLen",
			artist: "Legi",
			artist_url: "https://bsky.app/profile/homestar.bsky.social",
			desc: "A birthday gift from my boyfriend of Kaito and Len in their Flyway outfits from the Magical Mirai concert. As a bit of a troll, this pose is specifically referencing a shot from the fan animation for Twiddlefinger, a song that we had a bit of brainrot over.",
			date_str: "September 2025",
			tags: ["Vocaloid", "Kagamine Len", "KAITO", "KaiLen", "Gift"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/1f585d2561df.png"],
			thumbnail: "https://cdn.imgchest.com/files/11c1dcf91dbf.png",
			title: "Family Feud",
			artist: "Ivan Shinoda",
			artist_url: "https://x.com/ivanshinoda10",
			desc: "A collab with Mifi. The idea to do a Family Feud parody was his, and most of the script was done by me. You can also see a lot of the prototype designs that I would later refine for my modern AU designs.",
			date_str: "March 2023",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Male Morgan", "Lucina", "Joker", "Exalt Family", "Collab", "Comic"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/e1953b82ba30.png"],
			thumbnail: "https://cdn.imgchest.com/files/78136ff6bd54.png",
			title: "Summer Beach Party",
			artist: "RedKite",
			artist_url: "https://x.com/RedKite333?s=20",
			desc: "A large collab with several other people for a fun beach piece.",
			date_str: "June 2022",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Collab"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/756cf2654782.png"],
			thumbnail: "https://cdn.imgchest.com/files/e7f0111063a1.png",
			title: "Sleepover Gossip",
			artist: "Ly_art01",
			artist_url: "https://x.com/Ly_art01",
			desc: "A collab with DarthMarth. Robin and Lissa are having a fun sleepover, and gossipping a bit about their crushes. The sleepwear design for Robin was based on her armor break from Warriors.",
			date_str: "March 2022",
			tags: ["Fire Emblem", "Female Robin", "Lissa", "Collab"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/56105ab2cc8b.png"],
			thumbnail: "https://cdn.imgchest.com/files/56105ab2cc8b.png",
			title: "Robin Skill Issue",
			artist: "Rita",
			artist_url: "https://x.com/_anachaga",
			desc: "A gift from my friend, ZX!",
			date_str: "March 2022",
			tags: ["Fire Emblem", "Female Robin", "Gift"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/0a634ec73781.png"],
			thumbnail: "https://cdn.imgchest.com/files/59c8a5292729.png",
			title: "Hooters Robin and Lucina",
			artist: "Shugo",
			artist_url: "https://x.com/hiomaika",
			desc: "A collab with Yoostink and others. Lucina and Robin are hard at work earning tips so that they can +10 Brave Chrom.",
			date_str: "February 2022",
			tags: ["Fire Emblem", "Female Robin", "Lucina", "Lissa", "Ophelia", "Leonie", "Noire", "Collab"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/cfff7c580b47.png"],
			thumbnail: "https://cdn.imgchest.com/files/cfff7c580b47.png",
			title: "Robin Headpat",
			artist: "DeliiChan5",
			artist_url: null,
			desc: "A gift from DarthMarth of Robin receiving a headpat from Chrom.",
			date_str: "December 2021",
			tags: ["Fire Emblem", "Female Robin", "Chrobin", "Gift"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/7e143c96d8a0.png"],
			thumbnail: "https://cdn.imgchest.com/files/02c298f91b18.png",
			title: "Chrom with a Burger",
			artist: "SugarBunGaius",
			artist_url: "https://x.com/sugarbungaius",
			desc: "A gift from my friend, Miso, of Chrom with my boyfriend's favorite food, a burger.",
			date_str: "July 2021",
			tags: ["Fire Emblem", "Chrom", "Gift"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/05f2cf416e38.png"],
			thumbnail: "https://cdn.imgchest.com/files/b6cc97f90e08.png",
			title: "Robin with Boba Tea",
			artist: "SugarBunGaius",
			artist_url: "https://x.com/sugarbungaius",
			desc: "A gift from my friend, Miso, of Robin with my favorite food, boba tea.",
			date_str: "July 2021",
			tags: ["Fire Emblem", "Female Robin", "Gift"],
			hidden: false
		},				
		{
			src: ["https://cdn.imgchest.com/files/6e57cf4cfd2b.png"],
			thumbnail: "https://cdn.imgchest.com/files/838c55c9d4c3.png",
			title: "Summer Chrobin and Robin",
			artist: "Siren",
			artist_url: "https://x.com/ladylawga",
			desc: "A birthday gift from my friend, Silent. A cute scene of Chrom and Robin enjoying their beach date.",
			date_str: "September 2020",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Chrobin", "Gift"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/56d5c7dfaccd.png"],
			thumbnail: "https://cdn.imgchest.com/files/4aaeb05af7eb.png",
			title: "Family Outing",			
			artist: "Siren",
			artist_url: "https://x.com/ladylawga",
			desc: "A birthday gift from my friend, Silent. While Chrom and Robin are enjoying their moment of peace, Morgan is causing a bit of chaos for his sister in the background.",
			date_str: "September 2022",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Lucina", "Male Morgan", "Exalt Family", "Gift"],
			hidden: false
		},		
		{
			src: ["https://cdn.imgchest.com/files/c5b5268b89cc.png"],
			thumbnail: "https://cdn.imgchest.com/files/69349c5dce36.png",
			title: "Birthday Comic",
			artist: "Siren",
			artist_url: "https://x.com/ladylawga",
			desc: "A birthday gift from my friend, Silent. A fun comic that references some of my personal interests, like ballroom dancing or DDR.",
			date_str: "September 2023",
			tags: ["Fire Emblem", "Chrom", "Female Robin", "Lucina", "Male Morgan", "Exalt Family", "Gift", "Comic"],
			hidden: false
		},	
		{
			src: ["https://cdn.imgchest.com/files/3e7b1d2017c8.png"],
			thumbnail: "https://cdn.imgchest.com/files/6eb9e9ee6aed.png",
			title: "Dorothea and Lorenz",
			artist: "Siren",
			artist_url: "https://x.com/ladylawga",
			desc: "A birthday gift from my friend, Silent. As a funny backstory, I used to refer to this ship as Lorenzthea, which was misinterpreted as Lorenz and Lysithea. So when I received a fully colored illustration of Lorenz and Lysithea, I was very confused. Thankfully, Siren was gracious enough to do a quick re-do. From there onwards, I call the ship Dororenz instead haha.",
			date_str: "September 2021",
			tags: ["Fire Emblem 3H", "Dorothea", "Lorenz", "Dororenz", "Gift"],
			hidden: false
		}
	]
};
